export const Facultades = [
  "FCSE",
  "FCNI",
  "DPTO. DE CIENCIAS BÁSICAS",
  "DPTO. DE HUMANIDADES",
  "DPTO. DE IDIOMAS ",
];

export const TipoDeContrato = [
  "Carrera",
  "Tiempo completo",
  "Medio tiempo 11M",
  "Medio tiempo 4M",
];

export const Escalafon = [
  "Docente Experto",
  "Docente Auxiliar",
  "Docente Auxiliar 1",
  "Docente Asistente",
  "Docente Asociado",
  "Docente Titular",
];

export const Actividades = [
  {
    name: "Docencia Directa: Orientación de curso",
    mission: "Docencia",
    convention: "Docencia directa",
    product:
      "Plan de clase - acta de notas - guías orientadoras - parcial por corte",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Orientación de Módulo",
    mission: "Docencia",
    convention: "Docencia directa",
    product:
      "Plan de clase - acta de notas - guías orientadoras - parcial por corte",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Orientación de Módulo Virtual - Tutor",
    mission: "Docencia",
    convention: "Docencia directa",
    product: "Plan de modulo virtual",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Orientación de Módulo Virtual - Diseñador",
    mission: "Docencia",
    convention: "Docencia directa",
    product: "Diseño de modulo virtual",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Orientación de Módulo Virtual - Consejero",
    mission: "Docencia",
    convention: "Docencia directa",
    product: "Consejería a estudiantes",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Tutorías",
    mission: "Docencia",
    convention: "Docencia directa",
    product: "Informe final de la atención de tutorías de curso",
    description: "Tutoría en acompañamiento a estudiante",
    consolidated: "ODA7",
  },
  {
    name: "Preparación de clase: Metodología Pedagógica del Curso",
    mission: "Docencia",
    convention: "Otras",
    product: "Guías - talleres - métodos de aprendizajes",
    description: "Diseño metodológico del curso",
    consolidated: "Otras2",
  },
  {
    name: "Preparación de módulo: Metodología Pedagógica del Módulo",
    mission: "Docencia",
    convention: "Otras",
    product: "Guías - talleres - métodos de aprendizajes",
    description: "Diseño metodológico del módulo",
    consolidated: "Otras2",
  },
  {
    name: "ODA: PAD",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "Informe final del proyecto Acompañamiento Docente",
    description: "Proyecto acompañamiento docente",
    consolidated: "ODA1",
  },
  {
    name: "ODA: PAE",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "Informe final del proyecto Acompañamiento Docente",
    description: "Proyecto acompañamiento estudiante",
    consolidated: "ODA2",
  },
  {
    name: "ODA: Capacitación Docente",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "product final del seminario o módulo",
    description: "Participación en los cursos ofertados por la ODA",
    consolidated: "ODA8",
  },
  {
    name: "ODA: Evaluación Curricular",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "product final de la evaluación curricular del programa",
    description: "Desarrollar la evaluación curricular del programa",
    consolidated: "ODA3",
  },
  {
    name: "ODA: Diseño o Rediseño Plan de Curso",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "Entrega final del plan de curso del programa",
    description: "Elaboración del plan de curso",
    consolidated: "ODA4",
  },
  {
    name: "ODA: Renovación de Registro Calificado",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "Entrega final de las condiciones curriculares",
    description: "Construir las condiciones curriculares",
    consolidated: "ODA4",
  },
  {
    name: "Colectivo Docente: Plan de Clase",
    mission: "Docencia",
    convention: "Otras",
    product:
      "Actas de reunion - socialización de la línea del área de conocimiento",
    description: "Elaboración del plan de clase del curso",
    consolidated: "Otras3",
  },
  {
    name: "Colectivo Docente: Instrumento de Evaluación",
    mission: "Docencia",
    convention: "Otras",
    product: "Actas de reunion - instrumentos de evaluación",
    description:
      "Proponer temáticas para el desarrollo del instrumento de evaluación",
    consolidated: "Otras3",
  },
  {
    name: "Colectivo Docente: Permanencia",
    mission: "Docencia",
    convention: "Otras",
    product: "Informe de permanencia por corte",
    description: "Aplicar estrategias para la permanencia",
    consolidated: "Otras3",
  },
  {
    name: "Oficina de las Tic: Diseño de Módulos",
    mission: "Docencia",
    convention: "Otras",
    product: "Diseño de módulos del área de conocimiento",
    description: "Elaboración de módulos virtuales",
    consolidated: "Otras2",
  },
  {
    name: "OACA: Registro Calificado",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Entrega final de las condiciones institucionales y del programa",
    description: "Construir las condiciones institucionales y del programa",
    consolidated: "OACA1",
  },
  {
    name: "OACA: Renovación de Registro Calificado",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Entrega final de las condiciones institucionales  y del programa",
    description: "Construir las condiciones institucionales y del programa",
    consolidated: "OACA1",
  },
  {
    name: "OACA: Condiciones Iniciales",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Informe parcial o final de las condiciones iniciales",
    description:
      "Apoyo al proceso de cumplimiento de las condiciones iniciales",
    consolidated: "OACA3",
  },
  {
    name: "OACA: Acreditación",
    mission: "Docencia",
    convention: "Procesos OACA",
    product:
      "Informe parcial o final del documento de acreditación institucional y del programa",
    description:
      "Apoyo al proceso de acreditación del programa y de la institución",
    consolidated: "OACA4",
  },
  {
    name: "OACA: Autoevaluación Institucional",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Informe parcial o final de autoevaluación institucional",
    description: "Apoyar al proceso de autoevaluación institucional",
    consolidated: "OACA5",
  },
  {
    name: "OACA: Autoevaluación de Programa",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Informe parcial o final de autoevaluación del programa",
    description: "Apoyar al proceso de autoevaluación del programa",
    consolidated: "OACA2",
  },
  {
    name: "OACA: Vigía de Calidad",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "No aplica",
    description:
      "Apoyo a los procesos de calidad del programa y de la institución",
    consolidated: "OACA6",
  },
  {
    name: "Prospectiva: Del programa académico",
    mission: "Otros",
    convention: "Otras",
    product: "Informe parcial o final de la prospectiva del programa académico",
    description: "Apoyar al trabajo de prospectiva del programa",
    consolidated: "Otras1",
  },

  {
    name: "Comité: Curricular",
    mission: "Docencia",
    convention: "Comités",
    product: "Acta de los comités",
    description: "Participación en el comité curricular",
    consolidated: "Comités2",
  },
  {
    name: "Comité: Trabajos de Grado",
    mission: "Investigación",
    convention: "Comités",
    product: "Acta de los comités",
    description: "Participación en el comité de trabajos de grado",
    consolidated: "Comités1",
  },
  {
    name: "Comité: Autoevaluación",
    mission: "Docencia",
    convention: "Comités",
    product: "Acta de los comités",
    description: "Participación en el comité de trabajos de autoevaluación",
    consolidated: "Comités2",
  },
  {
    name: "Comité: Investigación y Semilleros",
    mission: "Investigación",
    convention: "Comités",
    product: "Acta de los comités",
    description:
      "Participación en el comité de trabajos de investigación y semilleros",
    consolidated: "Comités1",
  },
  {
    name: "Extensión: Graduados",
    mission: "Extensión",
    convention: "Extensión",
    product: "Informe final del seguimiento e impacto a graduados",
    description: "Participar en el seguimiento en impacto de graduados",
    consolidated: "Extensión1",
  },
  {
    name: "Extensión: Práctica Social",
    mission: "Extensión",
    convention: "Extensión",
    product: "Informe parcial o final de practicas sociales",
    description: "Acompañar y asesorar las practicas sociales",
    consolidated: "Extensión2",
  },
  {
    name: "Extensión: Educación Continua",
    mission: "Extensión",
    convention: "Extensión",
    product: "Informe final de propuestas y desarrollo de educación continua",
    description: "Apoyar procesos de formación en educación continua",
    consolidated: "Extensión3",
  },
  {
    name: "Extensión: Emprendimiento",
    mission: "Extensión",
    convention: "Extensión",
    product: "Informe final de proyectos de emprendimiento",
    description: "Realizar actividades o proyectos de apoyo al emprendimiento",
    consolidated: "Extensión4",
  },
  {
    name: "Investigación: Trabajos de Grado",
    mission: "Investigación",
    convention: "Investigación",
    product:
      "Informe estadístico de modalidades de trabajo de grado desarrolladas",
    description:
      "Participar en el apoyo a asesorías de los trabajos de grado según la línea",
    consolidated: "Investigación4",
  },
  {
    name: "Investigación: Grupo de Investigación",
    mission: "Investigación",
    convention: "Investigación",
    product: "Informe parcial o final del proyecto de investigación",
    description: "Realizar actividades o proyectos de apoyo al emprendimiento",
    consolidated: "Investigación1",
  },
  {
    name: "Investigación: Semilleros",
    mission: "Investigación",
    convention: "Investigación",
    product:
      "Informes parciales o finales de actividades desarrolladas en los semilleros de investigación",
    description:
      "Participar en la consolidación de los semilleros de investigación",
    consolidated: "Investigación2",
  },

  {
    name: "Investigación: Condiciones de Registro Calificado",
    mission: "Investigación",
    convention: "Investigación",
    product:
      "Informes parciales o finales de las condiciones de registro calificado",
    description: "Construcción de condiciones 5 y 6 del programa académico",
    consolidated: "Investigación3",
  },
  {
    name: "Coordinación: Participación reunión equipo programa",
    mission: "Otros",
    convention: "Otras",
    product: "Actas y registros de asistencia",
    description: "Participar en las reuniones del programa",
    consolidated: "Comités2",
  },

  {
    name: "Gestión y ejecución de convenios",
    mission: "Otros",
    convention: "Otras",
    product: "Informe de la gestión y ejecución de convenios",
    description: "Gestionar y ejecutar convenios",
    consolidated: "Otras2",
  },
];

export const Asignaturas = [
  "Accesorios I",
  "Accesorios II",
  "Accesorios III",
  "Accionamientos",
  "Accionamientos Eléctricos",
  "Accionamientos Eléctricos II",
  "Actuadores y Dispositivos de Maniobra",
  "Acuerdos Comerciales Internacionales",
  "Administración Ambiental",
  "Administración Bancaria",
  "Administración Comercial y de Servicios",
  "Administración de Empresas del Sector Hidrocarburos",
  "Administración de la Producción",
  "Administración de Obra",
  "Administración de Obras",
  "Administración de Redes",
  "Administración de Riesgo de Crédito y Liquidez",
  "Administración de Riesgo de Mercado y Operacional",
  "Administración de Salarios",
  "Administración de Servidores",
  "Administración de Servidores Avanzados",
  "Administración del Talento Humano",
  "Administración Deportiva",
  "Administración Financiera",
  "Administración General",
  "Administración para Ingenieros",
  "Administración Pública",
  "Administración y Gestión Empresarial",
  "Agroecología",
  "Agronomía I",
  "Agronomía II",
  "Aguas Subterráneas",
  "Aislamiento Eléctrico",
  "Álgebra Lineal",
  "Álgebra Matricial",
  "Álgebra Superior",
  "Ambiente y Desarrollo Sostenible",
  "Análisis Ambiental y Social",
  "Análisis de Circuitos Eléctricos I",
  "Análisis de Circuitos Eléctricos II",
  "Análisis de Costos",
  "Análisis de Crédito",
  "Análisis de Datos a Gran Escala",
  "Análisis de Estados Financieros",
  "Análisis de Estructuras",
  "Análisis de Integridad de Equipos",
  "Análisis de Mercados",
  "Análisis de Riesgos para Proyectos",
  "Análisis de Sistemas de Control",
  "Análisis de Sistemas de Control Digital",
  "Análisis de Sistemas Eléctricos de Potencia",
  "Análisis de Territorio",
  "Análisis Estructural",
  "Análisis Financiero",
  "Análisis Numérico",
  "Antenas",
  "Antenas y Microondas",
  "Antropología del Consumidor",
  "Antropometría y Nutrición",
  "Aplicaciones de Contenidos Educativos",
  "Aplicaciones Móviles",
  "Arquitectura de Software",
  "Arquitectura del Vestuario",
  "Arquitectura del Vestuario II",
  "Arquitectura Empresarial",
  "Arte, Cultura y Sociedad",
  "Aseguramiento de la Calidad",
  "Atletismo",
  "Atletismo I",
  "Atletismo II",
  "Auditoria de Gestión",
  "Auditoria de Sistemas",
  "Auditoria Financiera",
  "Autocad",
  "Autómatas y Lenguajes Formales",
  "Automatización Industrial",
  "Balance de Masas y Energía",
  "Balance de Materia y Energía",
  "Baloncesto",
  "Banca Digital",
  "Base de Datos Geográficos",
  "Bases de Datos",
  "Bases de Datos NoSQL",
  "Bienestar Social",
  "Bioagroenergias Alternativas",
  "Bioindicación",
  "Biología",
  "Biología General",
  "Biomasa Energética",
  "Biomecánica Aplicada",
  "Bioremediacion Acuática",
  "Bioremediación Terrestre",
  "Biotecnología en la Agroindustria",
  "Biotecnologías",
  "Bombeo y Compresión",
  "Boxeo",
  "Buenas Practicas en Turismo Sostenible",
  "CAD Electrónico",
  "Cálculo",
  "Calculo Diferencial",
  "Cálculo Diferencial",
  "Calculo Integral",
  "Cálculo Integral",
  "Calculo Multivariable",
  "Cálculo Multivariable",
  "Calidad Agroalimentaria",
  "Calidad de Energía",
  "Calidad de Software",
  "Calidad del Agua",
  "Capacitación y Desarrollo",
  "Cartografía Digital",
  "Cartografía para Gestión del Riesgo",
  "Cartografía y Topografía",
  "Centrales Eléctricas",
  "Ciencia, Tecnología y Sociedad",
  "Cine Literario",
  "Circuitos Digitales",
  "Circuitos Eléctricos I",
  "Circuitos Eléctricos II",
  "Climatología",
  "Cloud Computing",
  "Coaching",
  "Coaching Gerencial",
  "Colección",
  "Color y Concepto",
  "Comercio Electrónico",
  "Comercio Exterior",
  "Comercio Internacional",
  "Comercio Internacional Agroindustrial",
  "Competitividad",
  "Compiladores",
  "Comportamiento del Consumidor",
  "Comportamiento Organizacional",
  "Comunicación de la Moda",
  "Comunicación de Marketing",
  "Comunicación Digital",
  "Comunicación Organizacional",
  "Comunicaciones",
  "Comunicaciones Análogas",
  "Comunicaciones Avanzadas",
  "Comunicaciones Digitales I",
  "Comunicaciones Digitales II",
  "Comunicaciones Inalámbricas",
  "Comunicaciones Móviles",
  "Conmutación Digital",
  "Construcción de Ciudadanía",
  "Construcción de Marca",
  "Construcción Social del Territorio",
  "Contabilidad Bancaria",
  "Contabilidad de Instrumentos Financieros",
  "Contabilidad de Inventarios",
  "Contabilidad de Propiedad, Planta y Equipo",
  "Contabilidad e Inventarios",
  "Contabilidad en el Sector Hotelero",
  "Contabilidad en el Sector Solidario",
  "Contabilidad Financiera I",
  "Contabilidad Financiera II",
  "Contabilidad Financiera III",
  "Contabilidad Financiera IV",
  "Contabilidad Financiera V",
  "Contabilidad Fiscal I",
  "Contabilidad Fiscal II",
  "Contabilidad General",
  "Contabilidad Gubernamental",
  "Contabilidad Intermedia",
  "Contabilidad Simplificada",
  "Control de Calidad",
  "Control de Estructuras",
  "Control de la Producción",
  "Control de Obras Civiles",
  "Control de Producción",
  "Control Geométrico de Obras",
  "Control Interno",
  "Convertidores Electrónicos De Potencia",
  "Costos",
  "Costos de la Logística del Transporte",
  "Costos Gerenciales",
  "Costos I",
  "Costos II",
  "Costos y Presupuestos",
  "Creatividad Organizacional",
  "Creatividad y Diseño",
  "Cultura Ciudadana",
  "Cultura Física",
  "Deporte Adaptado e Inclusivo",
  "Deporte Formativo",
  "Deportes de Combate",
  "Desarrollo de Aplicaciones Multiplataforma",
  "Desarrollo de Contenidos Digitales y Multimediales",
  "Desarrollo de Videojuegos",
  "Desarrollo del Comportamiento Emprendedor",
  "Desarrollo Organizacional",
  "Desarrollo Social y Regional",
  "Desarrollo Sostenible",
  "Desarrollo Territorial",
  "Desarrollo Web",
  "Determinantes Sociales de la Vida Saludable",
  "Dibujo",
  "Dibujo Asistido por Computador",
  "Dibujo Computarizado",
  "Dibujo Sistematizado I",
  "Dibujo Sistematizado II",
  "Didáctica de la Educación Física y el Deporte",
  "Dinámica",
  "Dinámica de Sistemas",
  "Diseño de Acueductos y Alcantarillados",
  "Diseño de Bases de Datos",
  "Diseño de Elementos de Máquinas I",
  "Diseño de Elementos de Máquinas II",
  "Diseño de Estructuras de Hormigón Armado",
  "Diseño de Estructuras Metálicas",
  "Diseño de Experimentos",
  "Diseño de Obras Geotécnicas",
  "Diseño de Vías Terrestres y Pavimentos",
  "Diseño Digital I",
  "Diseño Digital II",
  "Diseño Experimental",
  "Diseño Funcional",
  "Diseño Web",
  "Diseño Web Avanzado",
  "Diseño y Distribución de Planta",
  "Diseño y Prototipado Rápido",
  "Dispositivos Electrónicos",
  "Dispositivos Electrónicos de Potencia",
  "Dispositivos Programables",
  "Domótica",
  "Ecología",
  "Ecología Ambiental",
  "E-Comerce",
  "Econometría Financiera",
  "Economía Ambiental",
  "Economía Colombiana",
  "Economía del Deporte",
  "Economía del Transporte",
  "Economía para Ingenieros",
  "Economía Solidaria",
  "Economía y Empresa",
  "Economía y Sociedad",
  "Ecosistemas Estratégicos",
  "Ecuaciones Diferenciales",
  "Educación Ambiental",
  "Eficiencia Energética y Energías Renovables en la Industria",
  "Eficiencia y Gestión Energética",
  "Ejercicio Físico en Poblaciones Especiales",
  "Ejercicio Físico y Salud",
  "El Excel y los Procesos Contables",
  "Electiva Complementaria I",
  "Electiva Complementaria II",
  "Electiva Complementaria III",
  "Electiva Complementaria IV",
  "Electiva Complementaria Salud Ocupacional",
  "Electiva de Combate - Lucha",
  "Electiva de Combate - Taekwondo",
  "Electiva de Conjunto - Baloncesto",
  "Electiva de Conjunto - Futbol",
  "Electiva de Conjunto - Voleybol",
  "Electiva de Marcas - Natación",
  "Electiva De Marcas - Patinaje",
  "Electiva de Profundización",
  "Electiva de Profundización I",
  "Electiva de Profundización II",
  "Electiva de Profundización III",
  "Electiva de Profundización IV",
  "Electiva de Profundización V",
  "Electiva de Profundización VI",
  "Electiva Inglés I Nivel Tecnológico",
  "Electiva Inglés II Nivel Tecnológico",
  "Electiva Inglés III Nivel Universitario",
  "Electivas Profundización I",
  "Electivas Profundización II",
  "Electivo de Profundización",
  "Electromagnetismo",
  "Electromedicina",
  "Electrónica Analógica",
  "Electrónica Analógica Avanzada",
  "Electrónica de Potencia",
  "Electrónica Digital",
  "Electrónica Digital Avanzada",
  "Electrónica Digital I",
  "Electrónica Digital II",
  "Electrónica e Instrumentación",
  "Electrónica General",
  "Electrónica I",
  "Electrónica II",
  "Electrónica III",
  "Electrónica Industrial",
  "Electroquímica Básica",
  "Emprenderismo",
  "Emprenderismo y Empresarismo",
  "Emprendimiento",
  "Empresarismo",
  "Energía Solar y Eólica",
  "Energía y Medio Ambiente",
  "Entorno de los Derechos Humanos",
  "Entorno Económico",
  "Entorno y Hábitat",
  "Epistemología",
  "Escalas de Variabilidad Climática",
  "Especies Pecuarias Promisorias",
  "Especies Vegetales Promisorias",
  "Establecimientos de Crédito",
  "Estadística",
  "Estadística Básica",
  "Estadística Inferencial",
  "Estadística para Ingenieros",
  "Estática",
  "Estilos de Enseñanza en el Entrenamiento Deportivo",
  "Estrategia de Precio",
  "Estrategia Publicitaria",
  "Estrategias de Negociación",
  "Estratigrafía y Tectónica II",
  "Estructura de Computadores",
  "Estructura de Datos",
  "Estructura de los Materiales",
  "Estructura de Portafolios de Renta Variable",
  "Estructuración de Portafolios de Renta Fija",
  "Estudios de Área Europa y Asia",
  "Estudios de Área Latinoamericana y Norte América",
  "Ética",
  "Ética del Hacking",
  "Ética Profesional",
  "Ética y Legislación Informática",
  "Etica y responsabilidad social del mercadeo",
  "Evaluación de Impactos Ambientales",
  "Evaluación de Mercados",
  "Evaluación de Proyectos",
  "Evaluación Económica y Social de Proyectos",
  "Evaluación Financiera de Proyectos",
  "Evaluación y Análisis Financiero",
  "Excel y la Contabilidad",
  "Exhibición Comercial",
  "Exhibicion y Merchandisig",
  "Expresión Corporal",
  "Fabricación de Equipos",
  "Fabricación Digital y Prototipado Rápido",
  "Fauna",
  "Figura Humana",
  "Financiamiento del Emprendimiento",
  "Finanzas Agroindustriales",
  "Finanzas Colaborativas",
  "Finanzas Internacionales",
  "Finanzas Públicas",
  "Física Moderna",
  "Fisiología del Ejercicio",
  "Flora",
  "Fondos Mutuos de Inversión",
  "Formulación de Proyectos",
  "Formulación y Evaluación de Proyectos",
  "Formulación y Gestión de Proyectos",
  "Fotogrametría Digital y Teledetección",
  "Franquicias",
  "Fuentes Alternativas de Energía",
  "Fuentes Alternativas de Energía II",
  "Fuentes Alternativas de Generación",
  "Fuentes Convencionales de Generación",
  "Fundamento Textil",
  "Fundamentos de Acueductos y Alcantarillados",
  "Fundamentos de Administración",
  "Fundamentos de Comercio Internacional",
  "Fundamentos de Distribución y Logística",
  "Fundamentos de Economía",
  "Fundamentos de Energías Renovables",
  "Fundamentos de Estados Financieros",
  "Fundamentos de Gestión Pública",
  "Fundamentos de la Comunicación Publicitaria",
  "Fundamentos de la Creatividad e Innovación",
  "Fundamentos de Logística",
  "Fundamentos de Mecánica",
  "Fundamentos de Microeconomia",
  "Fundamentos de POO",
  "Fundamentos de Presupuestos",
  "Fundamentos de Programación",
  "Fundamentos de Prototipado",
  "Fundamentos de Publicidad",
  "Fundamentos de Química",
  "Fundamentos de Sistemas de Información Geográfica",
  "Fundamentos de Urbanismo",
  "Fundamentos de Vias Terrestres",
  "Fútbol",
  "Fútbol Sala",
  "Gas Natural",
  "Generación Hidráulica",
  "Generación y Transporte de Energía",
  "Generación y Transporte de Energía Eléctrica",
  "Geodesia",
  "Geoestadística",
  "Geografía Económica",
  "Geografía Económica de Colombia",
  "Geografía y Sistemas de Información Geográfica I",
  "Geografía y Sistemas de Información Geográfica II",
  "Geología Ambiental",
  "Geometria Descriptiva",
  "Geometría Digital",
  "Geomorfología",
  "Geotecnia",
  "Gerencia Comercial",
  "Gerencia de Calidad",
  "Gerencia de la Calidad",
  "Gerencia de la Planeación Financiera",
  "Gerencia de las Instituciones Financieras",
  "Gerencia de Marketing",
  "Gerencia de Procesos",
  "Gerencia de Proyectos",
  "Gerencia del Servicio",
  "Gerencia Estratégica",
  "Gerencia Financiera",
  "Gerencia TIC",
  "Gerencia y Construcción de Marca",
  "Gestión de Áreas Protegidas",
  "Gestión de la Cadena de Abastecimiento",
  "Gestión de la Innovación",
  "Gestión de la Tecnología y Sistemas de Información",
  "Gestión de Mantenimiento",
  "Gestión de Mantenimiento Eléctrico",
  "Gestión de Mercados",
  "Gestión de Proyectos de Ingeniería",
  "Gestión de Proyectos de Software",
  "Gestión de Proyectos Industriales",
  "Gestión de Proyectos Informáticos",
  "Gestión de Recursos Humanos",
  "Gestión de Suministros y Almacenamientos",
  "Gestión de Ventas",
  "Gestión del Emprendimiento",
  "Gestión del Servicio",
  "Gestión Financiera",
  "Gestión Integral de Ecosistemas",
  "Gestión Logística y Distribución",
  "Gestión Pública",
  "Gestión Tecnológica",
  "Gestión Tributaria",
  "Gestión y Gobierno TI",
  "Gestión y Manejo de Sistemas Integrados",
  "Gestión y Producción de la Moda",
  "Gimnasia Básica",
  "Habilidades Comerciales",
  "Habilidades Comunicativas",
  "Habilidades de Negociación",
  "Hábitos de Vida Saludable",
  "Hacking Ético",
  "Halterolfilia",
  "Herramientas de Sistemas de Información Geográfica",
  "Herramientas Digitales",
  "Herramientas Gerenciales de Gestión",
  "Hidráulica Básica",
  "Hidrología",
  "Hidrología Superficial",
  "Historia de la Ciencia",
  "Historia Económica Territorial",
  "Hoja de cálculo para Negocios",
  "Huellas Ecológicas",
  "Identidad Diversidad e Inclusión",
  "Identificación de Efectos Ambientales",
  "Ilustración Digital",
  "Ilustración y Geometral",
  "Impacto Ambiental",
  "Impactos Ambientales",
  "Impactos en Ríos de Montaña",
  "Informática Aplicada",
  "Ingeniería de Software",
  "Ingeniería Legal",
  "Inglés I",
  "Inglés II",
  "Inglés III",
  "Inglés IV",
  "Iniciativa Empresarial",
  "Innovación",
  "Innovación y Competitividad",
  "Innovación y Desarrollo de Productos",
  "Inspeccion de Construccion de Obras",
  "Instalaciones Eléctricas e Iluminación I",
  "Instalaciones Eléctricas e Iluminación II",
  "Instalaciones Eléctricas Industriales",
  "Instituciones Financieras",
  "Instrumentación Básica",
  "Instrumentación Electrónica",
  "Instrumentación Electrónica De Procesos",
  "Instrumentación Industrial",
  "Instrumentos Virtuales y Sistemas Scada",
  "Integración Económica Internacional",
  "Inteligencia Artificial",
  "Inteligencia de Negocios",
  "Inteligencia Emocional",
  "Internet de las Cosas (IoT)",
  "Intervención Textil",
  "Interventoría de Obras de Infraestructura",
  "Introducción a la Banca",
  "Introducción a la Biodiversidad",
  "Introducción a la Contaduría",
  "Introducción a la Cultura Física y el Deporte",
  "Introducción a la Electrónica",
  "Introducción a la Geología",
  "Introducción a la Ingeniería",
  "Introducción a la Ingeniería Industrial",
  "Introducción a la Innovación",
  "Introducción a la Psicología",
  "Introducción a los Negocios Internacionales",
  "Introducción al Marketing",
  "Introducción al Mercadeo",
  "Introducción al Software",
  "Inversión en Franquicias",
  "Inversiones Socialmente Responsable",
  "Investigación Cualitativa de Mercados",
  "Investigación Cuantitativa de Mercados",
  "Investigación de Mercados",
  "Investigación de Operaciones",
  "ISO y Productividad",
  "Judo",
  "Juegos Básicos y Predeportivos",
  "Kinesiología del Deporte",
  "Laboratorio Circuitos Eléctricos",
  "Laboratorio Contable",
  "Laboratorio de Accionamientos Eléctricos",
  "Laboratorio de Accionamientos Eléctricos II",
  "Laboratorio de Comunicaciones",
  "Laboratorio de Comunicaciones Análogas",
  "Laboratorio de Comunicaciones Digitales",
  "Laboratorio de Comunicaciones Inalámbricas",
  "Laboratorio de Costos",
  "Laboratorio de Diseño Publicitario",
  "Laboratorio de Electrónica",
  "Laboratorio de Electrónica Analógica",
  "Laboratorio de Electrónica Analógica Avanzada",
  "Laboratorio de Electrónica Digital",
  "Laboratorio de Electrónica Digital I",
  "Laboratorio de Electrónica Digital II",
  "Laboratorio de Electrónica General",
  "Laboratorio de Electrónica I",
  "Laboratorio de Electrónica II",
  "Laboratorio de Electrónica III",
  "Laboratorio de Física",
  "Laboratorio de Fuentes Alternativas de Generación",
  "Laboratorio de Fuentes Convencionales de Generación",
  "Laboratorio de Instalaciones e Iluminación I",
  "Laboratorio de Instalaciones e Iluminación II",
  "Laboratorio de Máquinas Eléctricas",
  "Laboratorio de Máquinas Eléctricas I",
  "Laboratorio de Máquinas Eléctricas II",
  "Laboratorio de Medidas Eléctricas",
  "Laboratorio de Medidas y Circuitos Eléctricos",
  "Laboratorio de Procesos Industriales",
  "Laboratorio de Recurso Agua",
  "Laboratorio de Recurso Aire",
  "Laboratorio de Recurso Suelo",
  "Laboratorio de Refrigeración y Aire Acondicionado",
  "Laboratorio de Resistencia de Materiales",
  "Laboratorio de Sistemas de Control",
  "Laboratorio Empresarial",
  "Laboratorio y Diseño Publicitario",
  "Laboratorios de Electrónica Digital",
  "Laboratorios de Electrónica Digital Avanzada",
  "Legislación Ambiental",
  "Legislación Comercial",
  "Legislación de los Bienes y del Ambiente",
  "Legislación Deportiva",
  "Legislación Empresarial",
  "Legislación en Telecomunicaciones",
  "Legislación Financiera",
  "Legislación Internacional",
  "Legislación Laboral",
  "Levantamiento de Vías",
  "Levantamientos Fotogramétricos y Teledetección",
  "Levantamientos Topográficos I",
  "Levantamientos Topográficos II",
  "Licitaciones y Contratos",
  "Liderazgo Personal, Social y Empresarial",
  "Líneas de Producto",
  "Líneas y Redes Eléctricas I",
  "Líneas y Redes Eléctricas II",
  "Linux",
  "Literatura y Pensamiento",
  "Lógica del Transporte Férreo",
  "Lógica y Algoritmos",
  "Logística del Transporte Acuático",
  "Logística del Transporte Aéreo",
  "Logística del Transporte Carretero",
  "Logística y Cadena de Suministros",
  "Logística y Transporte",
  "Lucha Olímpica",
  "Macroeconomía",
  "Macroeconomía I",
  "Macroeconomía II",
  "Manejo Poscosecha",
  "Mantenimiento de Computadoras",
  "Mantenimiento de Obras Civiles",
  "Mantenimiento Industrial",
  "Mantenimiento Predictivo en Máquinas Eléctricas Basado Tcas Tramto Digitales de Señales",
  "Manufactura Esbelta",
  "Manufactura I",
  "Manufactura II",
  "Manufactura III",
  "Manufactura Sincrónica",
  "Máquinas Eléctricas",
  "Maquinas Eléctricas I",
  "Máquinas Eléctricas II",
  "Máquinas Hidráulicas",
  "Marcos de Trabajo",
  "Marketing Ambiental",
  "Marketing de Eventos",
  "Marketing de Eventos y Ferias",
  "Marketing Deportivo",
  "Marketing Digital - E-Commerce",
  "Marketing Financiero",
  "Marketing Internacional",
  "Marketing Participativo",
  "Marketing por Catálogo",
  "Marketing Relacional",
  "Marketing Turístico",
  "Marketing Turístico y Deportivo",
  "Marketing Verde",
  "Masaje Deportivo y Terapéutico",
  "Matemática Básica",
  "Matemática Financiera",
  "Matemática I",
  "Matemática II",
  "Matemáticas Discretas",
  "Matemáticas para las Operaciones Financieras",
  "Matlab",
  "Mecánica",
  "Mecánica Analítica",
  "Mecánica de Fluidos",
  "Mecánica de Fluidos e Hidráulica",
  "Mecánica de suelos",
  "Mecanismos",
  "Medicina Deportiva",
  "Medición y análisis de mercados",
  "Medios de Transmisión",
  "Medios y Cultura",
  "Mercadeo Agroindustrial",
  "Mercadeo de Turismo",
  "Mercadeo del Transporte",
  "Mercadeo Estratégico",
  "Mercadeo Sensorial",
  "Mercado de Capitales",
  "Mercado de Instrumentos de Cobertura",
  "Mercado de Títulos Valores",
  "Mercados de Energía",
  "Mercados Inmobiliarios",
  "Metodología de Investigación",
  "Metodología de Investigación I",
  "Metodología de Investigación II",
  "Metodología de la Investigación",
  "Metodología de la Investigación II de Ciencias del Deporte",
  "Metodología para Elaboración de Proyectos II",
  "Metodología para la Elaboración de Proyectos I",
  "Metodología para la Elaboración de Proyectos de Moda I",
  "Metodología y Entrenamiento de la Fuerza",
  "Métodos de Enseñanza y Aprendizaje en el Entrenamiento Deportivo",
  "Métodos y Tiempos",
  "Métodos y Tiempos de Producción",
  "Métricas del Marketing",
  "Metrología del Deporte",
  "Microbiología",
  "Microbiología Ambiental",
  "Microcontroladores",
  "Microeconomía",
  "Microeconomía I",
  "Microeconomía II",
  "Microeconomía-Macroeconomía",
  "Microfinanzas",
  "Microprocesadores I",
  "Microprocesadores II",
  "Mineralogía y Petrología II",
  "Mineria de Datos",
  "Moda y Contexto",
  "Modelamiento Constructivo",
  "Modelamiento para la Toma de Decisiones",
  "Modelamiento Sistémico",
  "Modelos de Negocio FINTECH",
  "Modelos de Planificación Deportiva",
  "Modelos Pedagógicos del Entrenamiento Deportivo",
  "Modos Condiciones y Estilos de Vida Saludable",
  "Modulación y Composición",
  "Morfofisiología",
  "Motivación Organizacional",
  "Motores de Bases de Datos",
  "Motores de Combustión Interna",
  "Motricidad",
  "Movilidad Urbana",
  "Natación",
  "Natación Paralímpica",
  "Negocio de Trading",
  "Negocios Empresariales",
  "Negocios Internacionales",
  "Neumática Básica",
  "Neuro - Marketing",
  "Normatividad en el Sector Eléctrico",
  "Normatividad Técnica del Dato Geográfico",
  "Nuevas Tecnologías de Desarrollo",
  "Nutrición Deportiva",
  "Obras Hidráulicas y Sanitarias",
  "Observatorio de Tendencias",
  "Ondas y Partículas",
  "Operación y Mantenimiento en Subestaciones Eléctricas",
  "Operación y Montaje Electromecánico",
  "Optativa I",
  "Optativa II",
  "Optativa III",
  "Optativa IV",
  "Ordenamiento Territorial",
  "Organización Empresarial",
  "Paisaje Urbano",
  "Paquete Contable",
  "Paquete Contable SV",
  "Patronaje Digital I",
  "Patronaje y Taller de Ensamble I",
  "Patronaje y Taller de Ensamble II",
  "Patronaje y Taller de Ensamble III",
  "Patrones de Software",
  "Pensamiento Algorítmico",
  "Pensamiento Creativo",
  "Pensamiento Creativo y Competitividad",
  "Pensamiento Social y Cultural Contemporáneo",
  "Pensamiento y Sistemas Políticos",
  "Percepción Audiovisual",
  "PERT y CPM",
  "Plan de Marketing",
  "Plan de Mercadeo",
  "Plan de Negocios",
  "Plan de Ordenamiento Territorial",
  "Plan Estratégico de Medios",
  "Planeación de Producción",
  "Planeación de Sistemas Informáticos",
  "Planeación del Transporte",
  "Planeacion Estratégica",
  "Planeación Tributaria",
  "Planeación y Gestión en Promoción y Mantenimiento de la Salud",
  "Planeación y Organización Deportiva",
  "Planeación y Producción Sostenible en Planta",
  "PLC",
  "Política de Precio",
  "Portafolio de Productos y Servicios Bancarios",
  "Portafolio Digital",
  "Potabilización del Agua",
  "Práctica de Levantamientos Topográficos I",
  "Práctica de Levantamientos Topográficos II",
  "Práctica Educativa y Formativa",
  "Práctica Profesional",
  "Prácticas de Baja Tensión",
  "Prácticas de Levantamiento de Vías",
  "Prácticas de Media Tensión",
  "Precálculo",
  "Preparación Física para el Alto Rendimiento",
  "Presupuestos",
  "Presupuestos y Programacion de Obra",
  "Principios de Automatización",
  "Principios de Base de Datos",
  "Principios de Estadística",
  "Principios de Programación",
  "Principios de Termodinámica",
  "Problemas Sociales Contemporáneos",
  "Procedimiento Tributario",
  "Procesamiento Digital de Imágenes",
  "Procesamiento Digital de Señales",
  "Proceso Administrativo",
  "Proceso Auditor",
  "Procesos Administrativos",
  "Procesos Agroindustriales",
  "Procesos Agroindustriales no Alimentarios",
  "Procesos de Conversión de Energía",
  "Procesos de Lectura y Escritura",
  "Procesos Industriales",
  "Procesos Licitatorios",
  "Procesos Mecánicos",
  "Procesos Mecánicos I",
  "Procesos Mecánicos II",
  "Procesos Radiofónicos",
  "Producción de Combustibles y Biocombustibles",
  "Producción de Texto",
  "Producción de Textos Profesionales",
  "Producción más Limpia",
  "Producción Sostenible",
  "Productos de Cobertura Financiera",
  "Productos y Servicios de Banca Corporativa",
  "Programación",
  "Programación Avanzada",
  "Programación con Bases de Datos",
  "Programación de Dispositivos",
  "Programación de Dispositivos Móviles",
  "Programación de Obra",
  "Programación de Sistemas Electrónicos",
  "Programación en Java",
  "Programación Java",
  "Programación Lineal",
  "Programación Multimedia",
  "Programación Neurolingüística",
  "Programación Orientada a Objetos",
  "Programación Orientada a Objetos Geográficos",
  "Programación WEB",
  "Promoción y Mantenimiento de la Salud",
  "Prospección Geotécnica",
  "Prospectiva",
  "Protecciones Eléctricas",
  "Protecciones Eléctricas II",
  "Protocolo y Relaciones Públicas",
  "Proyecto de Vida",
  "Proyectos de la Cultura Física y el Deporte",
  "Proyectos de la Cultura Física y el Deporte I",
  "Proyectos de la Cultura Física y el Deporte II",
  "Proyectos del Sector Hidrocarburos",
  "Psicología del Deporte",
  "Química Ambiental",
  "Química de Procesos",
  "Química Inorgánica",
  "Química Orgánica",
  "Realidad Aumentada",
  "Recreación",
  "Recuperación Ambiental de Suelo",
  "Recurso Agua",
  "Recurso Aire",
  "Recurso Suelo",
  "Redes",
  "Redes de Área Amplia",
  "Redes de Banda Ancha",
  "Redes Inalámbricas",
  "Redes y Comunicación de Datos",
  "Refinación de Hidrocarburos",
  "Refrigeración y Aire Acondicionado",
  "Regulación Comercial",
  "Regulación Laboral",
  "Relaciones Internacionales",
  "Residuos Sólidos",
  "Resistencia de Materiales",
  "Resolución de Conflictos",
  "Responsabilidad Social Empresarial",
  "Responsabilidad Social Y Competitividad Empresarial",
  "Restauraciones Ecológicas",
  "Retrospectiva de la Moda",
  "Revisoría Fiscal",
  "Riesgo Geólogico y Cambio Climático",
  "Robótica",
  "Robótica I",
  "Robótica II",
  "Salud Ocupacional Agroindustrial",
  "Saneamiento Básico y Ambiental",
  "Seguridad de las Tecnologías de la Información",
  "Seguridad en Redes",
  "Seguridad Industrial",
  "Seguridad y Salud en Trabajo y Medio Ambiente",
  "Selección y Evaluación de Tecnología",
  "Seminario de Grado I",
  "Seminario de Grado II",
  "Seminario de Tributaria",
  "Seminario Técnico",
  "Seminario Técnico II",
  "Semiótica Publicitaria",
  "Señales y Sistemas",
  "Servicios bajo Linux",
  "Servicios Eco sistémicos",
  "Sig y Desarrollo Agrícola Regional",
  "Simulación de Negocios",
  "Simulación de Negocios Internacionales",
  "Simulación de Procesos",
  "Simulación Digital",
  "Simulación Empresarial I",
  "Simulación Empresarial II",
  "Simulación Financiera en Hoja de Cálculo",
  "Simulación Gerencial",
  "Simulación Gerencial y Financiera",
  "Sistema de Audio y Video",
  "Sistema de Seguridad y Salud en el Trabajo",
  "Sistema Integrado de Gestión",
  "Sistemas Catastrales",
  "Sistemas de Control",
  "Sistemas de Gestión Ambiental",
  "Sistemas de Información",
  "Sistemas de Planeación",
  "Sistemas Descentralizados de Manejos de Aguas Residuales",
  "Sistemas Digitales",
  "Sistemas Electroneumáticos",
  "Sistemas Híbridos",
  "Sistemas Hidrogeométricos",
  "Sistematización Agrícola",
  "Sistematización Pecuaria",
  "Sociedades de Capitalización",
  "Sociedades de Servicios Financieros",
  "Software Especializado I",
  "Software Especializado II",
  "Software Libre para Trabajo Colaborativo",
  "Sostenibilidad del Territorio",
  "Sub Estaciones Eléctricas",
  "Suelos y Bosques",
  "Taekwondo",
  "Taller de Matemática Financiera",
  "Taller Financiero",
  "Taller Financiero SV",
  "Técnicas de Mantenimiento",
  "Tecnologías para Redes de Área Amplia",
  "Teledetección en Sistemas de Información Geográfica",
  "Telemática",
  "Tendencias Administrativas",
  "Tendencias Administrativas Americanas",
  "Tendencias Administrativas Europeas",
  "Tendencias Administrativas Japonesas",
  "Tendencias Administrativas Modernas",
  "Tendencias Físico Deportivas En El Entrenamiento Deportivo",
  "Teoría y Diseño en las Organizaciones",
  "Termodinámica",
  "Termodinámica Aplicada",
  "Territorios Inteligentes",
  "Tic en las Organizaciones",
  "Topografía para Actuaciones Urbanísticas",
  "Topografía para Redes y Líneas Eléctricas",
  "Topografia y Geomatica",
  "Toxicología",
  "Transferencia de Calor",
  "Tributaria I",
  "Tributaria II",
  "Tributaria III",
  "Valoración de Empresas",
  "Vibraciones Mecánicas",
  "Voleibol",
  "Voz IP",
  "Web Services",
];

export const Grupos = [
  "A001",
  "A002",
  "A003",
  "A004",
  "A005",
  "A006",
  "A007",
  "A008",
  "A009",
  "A010",
  "A011",
  "A012",
  "A013",
  "A014",
  "A015",
  "A016",
  "A017",
  "A018",
  "A019",
  "A020",
  "A041",
  "A042",
  "A043",
  "A044",
  "A045",
  "A046",
  "A047",
  "A048",
  "A049",
  "A050",
  "A051",
  "A052",
  "A053",
  "A054",
  "A055",
  "A056",
  "A057",
  "A058",
  "A059",
  "A060",
  "A111",
  "A112",
  "A113",
  "A114",
  "A115",
  "A116",
  "A117",
  "A118",
  "A119",
  "A120",
  "A121",
  "A122",
  "A123",
  "A124",
  "A125",
  "A126",
  "A127",
  "A128",
  "A129",
  "A130",
  "A211",
  "A212",
  "A213",
  "A214",
  "A215",
  "A216",
  "A217",
  "A218",
  "A219",
  "A220",
  "A261",
  "A262",
  "A263",
  "A264",
  "A265",
  "A266",
  "A267",
  "A268",
  "A269",
  "A270",
  "A271",
  "A272",
  "A273",
  "A274",
  "A275",
  "A276",
  "A277",
  "A278",
  "A279",
  "A280",
  "A281",
  "A282",
  "A283",
  "A284",
  "A285",
  "A286",
  "A287",
  "A288",
  "A289",
  "A290",
  "A291",
  "A292",
  "A293",
  "A294",
  "A295",
  "A296",
  "A297",
  "A298",
  "A299",
  "A300",
  "B001",
  "B002",
  "B003",
  "B004",
  "B005",
  "B006",
  "B007",
  "B008",
  "B009",
  "B010",
  "B011",
  "B012",
  "B013",
  "B014",
  "B015",
  "B016",
  "B017",
  "B018",
  "B019",
  "B020",
  "B041",
  "B042",
  "B043",
  "B044",
  "B045",
  "B046",
  "B047",
  "B048",
  "B049",
  "B050",
  "B051",
  "B052",
  "B053",
  "B054",
  "B055",
  "B056",
  "B057",
  "B058",
  "B059",
  "B060",
  "B111",
  "B112",
  "B113",
  "B114",
  "B115",
  "B116",
  "B117",
  "B118",
  "B119",
  "B120",
  "B121",
  "B122",
  "B123",
  "B124",
  "B125",
  "B126",
  "B127",
  "B128",
  "B129",
  "B130",
  "B211",
  "B212",
  "B213",
  "B214",
  "B215",
  "B216",
  "B217",
  "B218",
  "B219",
  "B220",
  "B261",
  "B262",
  "B263",
  "B264",
  "B265",
  "B266",
  "B267",
  "B268",
  "B269",
  "B270",
  "B271",
  "B272",
  "B273",
  "B274",
  "B275",
  "B276",
  "B277",
  "B278",
  "B279",
  "B280",
  "B281",
  "B282",
  "B283",
  "B284",
  "B285",
  "B286",
  "B287",
  "B288",
  "B289",
  "B290",
  "B291",
  "B292",
  "B293",
  "B294",
  "B295",
  "B296",
  "B297",
  "B298",
  "B299",
  "B300",
  "D001",
  "D002",
  "D003",
  "D004",
  "D005",
  "D006",
  "D007",
  "D008",
  "D009",
  "D010",
  "D011",
  "D012",
  "D013",
  "D014",
  "D015",
  "D016",
  "D017",
  "D018",
  "D019",
  "D020",
  "D041",
  "D042",
  "D043",
  "D044",
  "D045",
  "D046",
  "D047",
  "D048",
  "D049",
  "D050",
  "D051",
  "D052",
  "D053",
  "D054",
  "D055",
  "D056",
  "D057",
  "D058",
  "D059",
  "D060",
  "D111",
  "D112",
  "D113",
  "D114",
  "D115",
  "D116",
  "D117",
  "D118",
  "D119",
  "D120",
  "D121",
  "D122",
  "D123",
  "D124",
  "D125",
  "D126",
  "D127",
  "D128",
  "D129",
  "D130",
  "D211",
  "D212",
  "D213",
  "D214",
  "D215",
  "D216",
  "D217",
  "D218",
  "D219",
  "D220",
  "D261",
  "D262",
  "D263",
  "D264",
  "D265",
  "D266",
  "D267",
  "D268",
  "D269",
  "D270",
  "D271",
  "D272",
  "D273",
  "D274",
  "D275",
  "D276",
  "D277",
  "D278",
  "D279",
  "D280",
  "D281",
  "D282",
  "D283",
  "D284",
  "D285",
  "D286",
  "D287",
  "D288",
  "D289",
  "D290",
  "D291",
  "D292",
  "D293",
  "D294",
  "D295",
  "D296",
  "D297",
  "D298",
  "D299",
  "D300",
  "E001",
  "E002",
  "E003",
  "E004",
  "E005",
  "E006",
  "E007",
  "E008",
  "E009",
  "E010",
  "E011",
  "E012",
  "E013",
  "E014",
  "E015",
  "E016",
  "E017",
  "E018",
  "E019",
  "E020",
  "E041",
  "E042",
  "E043",
  "E044",
  "E045",
  "E046",
  "E047",
  "E048",
  "E049",
  "E050",
  "E051",
  "E052",
  "E053",
  "E054",
  "E055",
  "E056",
  "E057",
  "E058",
  "E059",
  "E060",
  "E111",
  "E112",
  "E113",
  "E114",
  "E115",
  "E116",
  "E117",
  "E118",
  "E119",
  "E120",
  "E121",
  "E122",
  "E123",
  "E124",
  "E125",
  "E126",
  "E127",
  "E128",
  "E129",
  "E130",
  "E211",
  "E212",
  "E213",
  "E214",
  "E215",
  "E216",
  "E217",
  "E218",
  "E219",
  "E220",
  "E261",
  "E262",
  "E263",
  "E264",
  "E265",
  "E266",
  "E267",
  "E268",
  "E269",
  "E270",
  "E271",
  "E272",
  "E273",
  "E274",
  "E275",
  "E276",
  "E277",
  "E278",
  "E279",
  "E280",
  "E281",
  "E282",
  "E283",
  "E284",
  "E285",
  "E286",
  "E287",
  "E288",
  "E289",
  "E290",
  "E291",
  "E292",
  "E293",
  "E294",
  "E295",
  "E296",
  "E297",
  "E298",
  "E299",
  "E300",
];

export const Misionales = [
  "Docencia",
  "Investigación",
  "Extensión",
  "OACA",
  "ODA",
  "Comités",
  "Otras",
];
