export const Facultades = [
  "FCSE",
  "FCNI",
  "DPTO. DE CIENCIAS BÁSICAS",
  "DPTO. DE HUMANIDADES",
  "DPTO. DE IDIOMAS ",
];

export const TipoDeContrato = [
  "Carrera",
  "Tiempo completo",
  "Medio tiempo 11M",
  "Medio tiempo 4M",
];

export const Escalafon = [
  "Docente Experto",
  "Docente Auxiliar",
  "Docente Auxiliar 1",
  "Docente Asistente",
  "Docente Asociado",
  "Docente Titular",
];

export const Actividades = [
  {
    name: "Docencia Directa: Orientación de curso",
    mission: "Docencia",
    convention: "Docencia directa",
    product:
      "Plan de clase - acta de notas - guías orientadoras - parcial por corte",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Orientación de Módulo",
    mission: "Docencia",
    convention: "Docencia directa",
    product:
      "Plan de clase - acta de notas - guías orientadoras - parcial por corte",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Orientación de Módulo Virtual - Tutor",
    mission: "Docencia",
    convention: "Docencia directa",
    product: "Plan de modulo virtual",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Orientación de Módulo Virtual - Diseñador",
    mission: "Docencia",
    convention: "Docencia directa",
    product: "Diseño de modulo virtual",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Orientación de Módulo Virtual - Consejero",
    mission: "Docencia",
    convention: "Docencia directa",
    product: "Consejería a estudiantes",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Tutorías",
    mission: "Docencia",
    convention: "Docencia directa",
    product: "Informe final de la atención de tutorías de curso",
    description: "Tutoría en acompañamiento a estudiante",
    consolidated: "ODA7",
  },
  {
    name: "Preparación de clase: Metodología Pedagógica del Curso",
    mission: "Docencia",
    convention: "Otras",
    product: "Guías - talleres - métodos de aprendizajes",
    description: "Diseño metodológico del curso",
    consolidated: "Otras2",
  },
  {
    name: "Preparación de módulo: Metodología Pedagógica del Módulo",
    mission: "Docencia",
    convention: "Otras",
    product: "Guías - talleres - métodos de aprendizajes",
    description: "Diseño metodológico del módulo",
    consolidated: "Otras2",
  },
  {
    name: "ODA: PAD",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "Informe final del proyecto Acompañamiento Docente",
    description: "Proyecto acompañamiento docente",
    consolidated: "ODA1",
  },
  {
    name: "ODA: PAE",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "Informe final del proyecto Acompañamiento Docente",
    description: "Proyecto acompañamiento estudiante",
    consolidated: "ODA2",
  },
  {
    name: "ODA: Capacitación Docente",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "product final del seminario o módulo",
    description: "Participación en los cursos ofertados por la ODA",
    consolidated: "ODA8",
  },
  {
    name: "ODA: Evaluación Curricular",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "product final de la evaluación curricular del programa",
    description: "Desarrollar la evaluación curricular del programa",
    consolidated: "ODA3",
  },
  {
    name: "ODA: Diseño o Rediseño Plan de Curso",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "Entrega final del plan de curso del programa",
    description: "Elaboración del plan de curso",
    consolidated: "ODA4",
  },
  {
    name: "ODA: Renovación de Registro Calificado",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "Entrega final de las condiciones curriculares",
    description: "Construir las condiciones curriculares",
    consolidated: "ODA4",
  },
  {
    name: "Colectivo Docente: Plan de Clase",
    mission: "Docencia",
    convention: "Otras",
    product:
      "Actas de reunion - socialización de la línea del área de conocimiento",
    description: "Elaboración del plan de clase del curso",
    consolidated: "Otras3",
  },
  {
    name: "Colectivo Docente: Instrumento de Evaluación",
    mission: "Docencia",
    convention: "Otras",
    product: "Actas de reunion - instrumentos de evaluación",
    description:
      "Proponer temáticas para el desarrollo del instrumento de evaluación",
    consolidated: "Otras3",
  },
  {
    name: "Colectivo Docente: Permanencia",
    mission: "Docencia",
    convention: "Otras",
    product: "Informe de permanencia por corte",
    description: "Aplicar estrategias para la permanencia",
    consolidated: "Otras3",
  },
  {
    name: "Oficina de las Tic: Diseño de Módulos",
    mission: "Docencia",
    convention: "Otras",
    product: "Diseño de módulos del área de conocimiento",
    description: "Elaboración de módulos virtuales",
    consolidated: "Otras2",
  },
  {
    name: "OACA: Registro Calificado",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Entrega final de las condiciones institucionales y del programa",
    description: "Construir las condiciones institucionales y del programa",
    consolidated: "OACA1",
  },
  {
    name: "OACA: Renovación de Registro Calificado",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Entrega final de las condiciones institucionales  y del programa",
    description: "Construir las condiciones institucionales y del programa",
    consolidated: "OACA1",
  },
  {
    name: "OACA: Condiciones Iniciales",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Informe parcial o final de las condiciones iniciales",
    description:
      "Apoyo al proceso de cumplimiento de las condiciones iniciales",
    consolidated: "OACA3",
  },
  {
    name: "OACA: Acreditación",
    mission: "Docencia",
    convention: "Procesos OACA",
    product:
      "Informe parcial o final del documento de acreditación institucional y del programa",
    description:
      "Apoyo al proceso de acreditación del programa y de la institución",
    consolidated: "OACA4",
  },
  {
    name: "OACA: Autoevaluación Institucional",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Informe parcial o final de autoevaluación institucional",
    description: "Apoyar al proceso de autoevaluación institucional",
    consolidated: "OACA5",
  },
  {
    name: "OACA: Autoevaluación de Programa",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Informe parcial o final de autoevaluación del programa",
    description: "Apoyar al proceso de autoevaluación del programa",
    consolidated: "OACA2",
  },
  {
    name: "OACA: Vigía de Calidad",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "No aplica",
    description:
      "Apoyo a los procesos de calidad del programa y de la institución",
    consolidated: "OACA6",
  },
  {
    name: "Prospectiva: Del programa académico",
    mission: "Otros",
    convention: "Otras",
    product: "Informe parcial o final de la prospectiva del programa académico",
    description: "Apoyar al trabajo de prospectiva del programa",
    consolidated: "Otras1",
  },

  {
    name: "Comité: Curricular",
    mission: "Docencia",
    convention: "Comités",
    product: "Acta de los comités",
    description: "Participación en el comité curricular",
    consolidated: "Comités2",
  },
  {
    name: "Comité: Trabajos de Grado",
    mission: "Investigación",
    convention: "Comités",
    product: "Acta de los comités",
    description: "Participación en el comité de trabajos de grado",
    consolidated: "Comités1",
  },
  {
    name: "Comité: Autoevaluación",
    mission: "Docencia",
    convention: "Comités",
    product: "Acta de los comités",
    description: "Participación en el comité de trabajos de autoevaluación",
    consolidated: "Comités2",
  },
  {
    name: "Comité: Investigación y Semilleros",
    mission: "Investigación",
    convention: "Comités",
    product: "Acta de los comités",
    description:
      "Participación en el comité de trabajos de investigación y semilleros",
    consolidated: "Comités1",
  },
  {
    name: "Extensión: Graduados",
    mission: "Extensión",
    convention: "Extensión",
    product: "Informe final del seguimiento e impacto a graduados",
    description: "Participar en el seguimiento en impacto de graduados",
    consolidated: "Extensión1",
  },
  {
    name: "Extensión: Práctica Social",
    mission: "Extensión",
    convention: "Extensión",
    product: "Informe parcial o final de practicas sociales",
    description: "Acompañar y asesorar las practicas sociales",
    consolidated: "Extensión2",
  },
  {
    name: "Extensión: Educación Continua",
    mission: "Extensión",
    convention: "Extensión",
    product: "Informe final de propuestas y desarrollo de educación continua",
    description: "Apoyar procesos de formación en educación continua",
    consolidated: "Extensión3",
  },
  {
    name: "Extensión: Emprendimiento",
    mission: "Extensión",
    convention: "Extensión",
    product: "Informe final de proyectos de emprendimiento",
    description: "Realizar actividades o proyectos de apoyo al emprendimiento",
    consolidated: "Extensión4",
  },
  {
    name: "Investigación: Trabajos de Grado",
    mission: "Investigación",
    convention: "Investigación",
    product:
      "Informe estadístico de modalidades de trabajo de grado desarrolladas",
    description:
      "Participar en el apoyo a asesorías de los trabajos de grado según la línea",
    consolidated: "Investigación4",
  },
  {
    name: "Investigación: Grupo de Investigación",
    mission: "Investigación",
    convention: "Investigación",
    product: "Informe parcial o final del proyecto de investigación",
    description: "Realizar actividades o proyectos de apoyo al emprendimiento",
    consolidated: "Investigación1",
  },
  {
    name: "Investigación: Semilleros",
    mission: "Investigación",
    convention: "Investigación",
    product:
      "Informes parciales o finales de actividades desarrolladas en los semilleros de investigación",
    description:
      "Participar en la consolidación de los semilleros de investigación",
    consolidated: "Investigación2",
  },

  {
    name: "Investigación: Condiciones de Registro Calificado",
    mission: "Investigación",
    convention: "Investigación",
    product:
      "Informes parciales o finales de las condiciones de registro calificado",
    description: "Construcción de condiciones 5 y 6 del programa académico",
    consolidated: "Investigación3",
  },
  {
    name: "Coordinación: Participación reunión equipo programa",
    mission: "Otros",
    convention: "Otras",
    product: "Actas y registros de asistencia",
    description: "Participar en las reuniones del programa",
    consolidated: "Comités2",
  },

  {
    name: "Gestión y ejecución de convenios",
    mission: "Otros",
    convention: "Otras",
    product: "Informe de la gestión y ejecución de convenios",
    description: "Gestionar y ejecutar convenios",
    consolidated: "Otras2",
  },
];

export const Asignaturas = [
  "LITERATURA Y PENSAMIENTO",
  "ALGEBRA MATRICIAL",
  "COMUNICACION ORGANIZACIONAL",
  "MERCADEO ESTRATEGICO",
  "PROPEDEUTICA DE LA ADMINISTRACION",
  "TEORIA Y DISEÑO ORGANIZACIONAL",
  "ELECTIVA INGLES III NIVEL UNIVERSITARIO",
  "GESTION DEL SERVICIO",
  "ECONOMIA COLOMBIANA",
  "ESTADISTICA INFERENCIAL",
  "PROGRAMACION LINEAL",
  "TENDENCIAS ADMINISTRATIVAS MODERNAS",
  "ADMINISTRACION DE LA CALIDAD",
  "CASOS Y PROYECTOS EMPRESARIALES",
  "ADMINISTRACION AMBIENTAL",
  "HERRAMIENTAS GERENCIALES DE CONTROL",
  "INVESTIGACION DE OPERACIONES",
  "PENSAMIENTO CREATIVO",
  "PLANEACION FINANCIERA",
  "DESARROLLO ORGANIZACIONAL",
  "ADMINISTRACION DE PROCESOS",
  "MARKETING RELACIONAL",
  "HERRAMIENTAS GERENCIALES DE GESTION",
  "MARKETING INTERNACIONAL",
  "SIMULACION ADMINISTRATIVA Y GERENCIAL",
  "AUDITORIA DE GESTION",
  "CONSTRUCCIÓN DE CIUDADANIA",
  "CONTABILIDAD SUPERIOR",
  "MACROECONOMIA",
  "PRESUPUESTOS",
  "PROCEDIMIENTO TRIBUTARIO",
  "ETICA PROFESIONAL",
  "REGULACION INTERNACIONAL",
  "AUDITORIA FINANCIERA",
  "COSTOS GERENCIALES",
  "CONTABILIDAD EN EL SECTOR SOLIDARIO",
  "INVESTIGACION CONTABLE",
  "METODOLOGIA PARA LA ELABORACION DE PROYECTOS II",
  "AUDITORIA DE SISTEMAS",
  "GERENCIA FINANCIERA",
  "PLANEACION TRIBUTARIA",
  "CONTABILIDAD INTERNACIONAL",
  "CONTABILIDAD EN EL SECTOR HOTELERO",
  "LABORATORIO DE COSTOS",
  "CONTABILIDAD GUBERNAMENTAL",
  "NEGOCIOS INTERNACIONALES",
  "ADMINISTRACION PUBLICA",
  "EVALUACION DE PROYECTOS",
  "REVISORIA FISCAL",
  "SEMINARIO DE TRIBUTARIA",
  "DISEÑO DE ELEMENTOS DE MAQUINAS I",
  "ECONOMIA PARA INGENIEROS",
  "ALGEBRA LINEAL",
  "DINAMICA",
  "ECUACIONES DIFERENCIALES",
  "LABORATORIO DE RESISTENCIA DE MATERIALES",
  "DISEÑO DE ELEMENTOS DE MAQUINAS II",
  "ANALISIS DE SISTEMAS ELECTRICOS DE POTENCIA",
  "ANALISIS NUMERICO",
  "ELECTRONICA INDUSTRIAL",
  "MECANICA DE FLUIDOS",
  "LABORATORIO DE SISTEMAS DE CONTROL",
  "PROTECCIONES ELECTRICAS",
  "SISTEMAS DE CONTROL",
  "ANALISIS DE INTEGRIDAD DE EQUIPOS",
  "ESTADISTICA PARA INGENIEROS",
  "TERMODINAMICA APLICADA",
  "AUTOMATIZACION INDUSTRIAL",
  "GENERACION Y TRANSPORTE DE ENERGIA ELECTRICA",
  "MAQUINAS HIDRAULICAS",
  "GESTION DE MANTENIMIENTO",
  "GESTION DE PROYECTOS INDUSTRIALES",
  "TRANSFERENCIA DE CALOR",
  "TEORIA CONTABLE",
  "TRIBUTARIA II",
  "TALLER FINANCIERO",
  "ANALISIS FINANCIERO",
  "METODOLOGIA PARA LA ELABORACION DE PROYECTOS I",
  "LABORATORIO CONTABLE",
  "CONTABILIDAD INTERMEDIA",
  "ALGEBRA SUPERIOR",
  "CALCULO DIFERENCIAL",
  "HABILIDADES COMUNICATIVAS",
  "PROCESOS DE LECTURA Y ESCRITURA",
  "QUIMICA DE PROCESOS",
  "CULTURA FISICA",
  "CIRCUITOS ELECTRICOS I",
  "ELECTROQUÍMICA BASICA",
  "INGLES I",
  "MECANICA",
  "CALCULO INTEGRAL",
  "BALANCE DE MATERIA Y ENERGIA",
  "CIRCUITOS ELECTRICOS II",
  "ELECTROMAGNETISMO",
  "EPISTEMOLOGIA",
  "INGLES II",
  "CALCULO MULTIVARIABLE",
  "ENERGIA Y MEDIO AMBIENTE",
  "ELECTRONICA E INSTRUMENTACION",
  "LABORATORIO DE FISICA",
  "LIDERAZGO PERSONAL, SOCIAL Y EMPRESARIAL",
  "PRODUCCION DE COMBUSTIBLES Y BIOCOMBUSTIBLES",
  "TERMODINAMICA",
  "BIOMASA ENERGETICA",
  "FUENTES ALTERNATIVAS DE GENERACION",
  "GESTION TECNOLOGICA",
  "LABORATORIO DE FUENTES ALTERNATIVAS DE GENERACION",
  "PROCESOS DE CONVERSION DE ENERGIA",
  "SEMINARIO DE GRADO I",
  "EFICIENCIA Y GESTION ENERGETICA",
  "SISTEMAS HIBRIDOS",
  "FUENTES CONVENCIONALES DE GENERACION",
  "LABORATORIO DE FUENTES CONVENCIONALES DE GENERACION",
  "SEMINARIO DE GRADO II",
  "ADMINISTRACION GENERAL",
  "CONTABILIDAD GENERAL",
  "MATEMÁTICAS I",
  "MICROECONOMIA",
  "FUNDAMENTOS DE MARKETING",
  "LEGISLACION EMPRESARIAL",
  "MATEMÁTICAS II",
  "COSTOS",
  "ADMINISTRACION COMERCIAL Y DE SERVICIOS",
  "FUNDAMENTOS DE LA CREATIVIDAD Y EMPRENDIMIENTO",
  "INFORMATICA APLICADA",
  "MATEMATICA FINANCIERA",
  "PROCESO ADMINISTRATIVO",
  "ADMINISTRACION DEL TALENTO HUMANO",
  "FUNDAMENTOS DE PRESUPUESTOS",
  "INNOVACION Y COMPETITIVIDAD",
  "PROBLEMAS SOCIALES CONTEMPORANEOS",
  "ADMINISTRACION DE LA PRODUCCION",
  "RESOLUCION DE CONFLICTOS",
  "RESPONSABILIDAD SOCIAL EMPRESARIAL",
  "ESTADISTICA",
  "ELECTIVA DE PROFUNDIZACIÓN III",
  "FORMULACIÓN Y EVALUACIÓN DE PROYECTOS",
  "LABORATORIO EMPRESARIAL",
  "ELECTIVA DE PROFUNDIZACIÓN IV",
  "OPTATIVA IV",
  "SISTEMAS DE SERVICIOS INDUSTRIALES",
  "SISTEMAS DE ALMACENAMIENTO DE ENERGÍA",
  "ELECTIVA DE PROFUNDIZACIÓN V",
  "EMPRENDIMIENTO",
  "MERCADOS ENERGÉTICOS",
  "MODELAMIENTO Y SIMULACIÓN DE SISTEMAS ENERGÉTICOS",
  "ELECTIVA DE PROFUNDIZACIÓN VI",
  "FINANZAS PUBLICAS",
  "INNOVACIÓN EMPRESARIAL",
  "SIMULACIÓN EMPRESARIAL",
  "ECONOMIA Y EMPRESA",
  "INTRODUCCION A LA CONTADURIA",
  "CONTABILIDAD FINANCIERA I",
  "CONTABILIDAD FISCAL I",
  "OPTATIVA I (EMPRENDERISMO Y EMPRESARISMO)",
  "GEOMETRIA DESCRIPTIVA",
  "DIBUJO COMPUTARIZADO",
  "PRINCIPIOS DE PROGRAMACIÓN",
  "ESTATICA",
  "AMBIENTE Y DESARROLLO SOSTENIBLE",
  "PROCESOS MECANICOS",
  "ELECTRONICA GENERAL",
  "MAQUINAS ELECTRICAS I",
  "RESISTENCIA DE MATERIALES",
  "MICROCONTROLADORES",
  "MANTENIMIENTO INDUSTRIAL",
  "SISTEMAS ELECTRONEUMATICOS",
  "INSTALACIONES ELECTRICAS INDUSTRIALES",
  "INSTRUMENTACION INDUSTRIAL",
  "MAQUINAS ELECTRICAS II",
  "OPERACION Y MONTAJE ELECTROMECANICO",
  "REFRIGERACION Y AIRE ACONDICIONADO",
  "ACCIONAMIENTOS ELECTRICOS",
  "MECANISMOS",
  "LABORATORIO DE ACCIONAMIENTOS ELECTRICOS",
  "LABORATORIO DE REFRIGERACION Y AIRE ACONDICIONADO",
  "LABORATORIO DE ELECTRONICA",
  "LABORATORIO DE MAQUINAS ELECTRICAS II",
  "NEUMATICA BASICA",
  "GEOPOLÍTICA DE LA ENERGÍA",
  "INGLÉS III",
  "OPTATIVA III",
  "FORMULACIÓN Y EVALUACIÓN DE PROYECTOS DE ENERGÍA",
  "SEMINARIO DE GRADO IV",
];

export const Grupos = [
  "E001",
  "E001D",
  "E002",
  "E041",
  "E041B",
  "E041D",
  "E041P",
  "E042",
  "E042B",
  "E042P",
  "E111",
  "E111B",
  "E111D",
  "E111P",
  "E112",
  "E112B",
  "E112P",
  "E113",
  "E113B",
  "E114",
  "E114R",
  "E115R",
  "E261",
  "E261B",
  "E262",
];

export const Misionales = [
  "Docencia",
  "Investigación",
  "Extensión",
  "OACA",
  "ODA",
  "Comités",
  "Otras",
];
