export const Facultades = [
  "FCSE",
  "FCNI",
  "DPTO. DE CIENCIAS BÁSICAS",
  "DPTO. DE HUMANIDADES",
  "DPTO. DE IDIOMAS ",
];

export const TipoDeContrato = [
  "Carrera",
  "Tiempo completo",
  "Medio tiempo 11M",
  "Medio tiempo 4M",
];

export const Escalafon = [
  "Docente Experto",
  "Docente Auxiliar",
  "Docente Auxiliar 1",
  "Docente Asistente",
  "Docente Asociado",
  "Docente Titular",
];

export const Actividades = [
  {
    name: "Docencia Directa: Orientación de curso",
    mission: "Docencia",
    convention: "Docencia directa",
    product:
      "Plan de clase - acta de notas - guías orientadoras - parcial por corte",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Orientación de Módulo",
    mission: "Docencia",
    convention: "Docencia directa",
    product:
      "Plan de clase - acta de notas - guías orientadoras - parcial por corte",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Orientación de Módulo Virtual - Tutor",
    mission: "Docencia",
    convention: "Docencia directa",
    product: "Plan de modulo virtual",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Orientación de Módulo Virtual - Diseñador",
    mission: "Docencia",
    convention: "Docencia directa",
    product: "Diseño de modulo virtual",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Orientación de Módulo Virtual - Consejero",
    mission: "Docencia",
    convention: "Docencia directa",
    product: "Consejería a estudiantes",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Tutorías",
    mission: "Docencia",
    convention: "Docencia directa",
    product: "Informe final de la atención de tutorías de curso",
    description: "Tutoría en acompañamiento a estudiante",
    consolidated: "ODA7",
  },
  {
    name: "Preparación de clase: Metodología Pedagógica del Curso",
    mission: "Docencia",
    convention: "Otras",
    product: "Guías - talleres - métodos de aprendizajes",
    description: "Diseño metodológico del curso",
    consolidated: "Otras2",
  },
  {
    name: "Preparación de módulo: Metodología Pedagógica del Módulo",
    mission: "Docencia",
    convention: "Otras",
    product: "Guías - talleres - métodos de aprendizajes",
    description: "Diseño metodológico del módulo",
    consolidated: "Otras2",
  },
  {
    name: "ODA: PAD",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "Informe final del proyecto Acompañamiento Docente",
    description: "Proyecto acompañamiento docente",
    consolidated: "ODA1",
  },
  {
    name: "ODA: PAE",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "Informe final del proyecto Acompañamiento Docente",
    description: "Proyecto acompañamiento estudiante",
    consolidated: "ODA2",
  },
  {
    name: "ODA: Capacitación Docente",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "product final del seminario o módulo",
    description: "Participación en los cursos ofertados por la ODA",
    consolidated: "ODA8",
  },
  {
    name: "ODA: Evaluación Curricular",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "product final de la evaluación curricular del programa",
    description: "Desarrollar la evaluación curricular del programa",
    consolidated: "ODA3",
  },
  {
    name: "ODA: Diseño o Rediseño Plan de Curso",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "Entrega final del plan de curso del programa",
    description: "Elaboración del plan de curso",
    consolidated: "ODA4",
  },
  {
    name: "ODA: Renovación de Registro Calificado",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "Entrega final de las condiciones curriculares",
    description: "Construir las condiciones curriculares",
    consolidated: "ODA4",
  },
  {
    name: "Colectivo Docente: Plan de Clase",
    mission: "Docencia",
    convention: "Otras",
    product:
      "Actas de reunion - socialización de la línea del área de conocimiento",
    description: "Elaboración del plan de clase del curso",
    consolidated: "Otras3",
  },
  {
    name: "Colectivo Docente: Instrumento de Evaluación",
    mission: "Docencia",
    convention: "Otras",
    product: "Actas de reunion - instrumentos de evaluación",
    description:
      "Proponer temáticas para el desarrollo del instrumento de evaluación",
    consolidated: "Otras3",
  },
  {
    name: "Colectivo Docente: Permanencia",
    mission: "Docencia",
    convention: "Otras",
    product: "Informe de permanencia por corte",
    description: "Aplicar estrategias para la permanencia",
    consolidated: "Otras3",
  },
  {
    name: "Oficina de las Tic: Diseño de Módulos",
    mission: "Docencia",
    convention: "Otras",
    product: "Diseño de módulos del área de conocimiento",
    description: "Elaboración de módulos virtuales",
    consolidated: "Otras2",
  },
  {
    name: "OACA: Registro Calificado",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Entrega final de las condiciones institucionales y del programa",
    description: "Construir las condiciones institucionales y del programa",
    consolidated: "OACA1",
  },
  {
    name: "OACA: Renovación de Registro Calificado",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Entrega final de las condiciones institucionales  y del programa",
    description: "Construir las condiciones institucionales y del programa",
    consolidated: "OACA1",
  },
  {
    name: "OACA: Condiciones Iniciales",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Informe parcial o final de las condiciones iniciales",
    description:
      "Apoyo al proceso de cumplimiento de las condiciones iniciales",
    consolidated: "OACA3",
  },
  {
    name: "OACA: Acreditación",
    mission: "Docencia",
    convention: "Procesos OACA",
    product:
      "Informe parcial o final del documento de acreditación institucional y del programa",
    description:
      "Apoyo al proceso de acreditación del programa y de la institución",
    consolidated: "OACA4",
  },
  {
    name: "OACA: Autoevaluación Institucional",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Informe parcial o final de autoevaluación institucional",
    description: "Apoyar al proceso de autoevaluación institucional",
    consolidated: "OACA5",
  },
  {
    name: "OACA: Autoevaluación de Programa",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Informe parcial o final de autoevaluación del programa",
    description: "Apoyar al proceso de autoevaluación del programa",
    consolidated: "OACA2",
  },
  {
    name: "OACA: Vigía de Calidad",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "No aplica",
    description:
      "Apoyo a los procesos de calidad del programa y de la institución",
    consolidated: "OACA6",
  },
  {
    name: "Prospectiva: Del programa académico",
    mission: "Otros",
    convention: "Otras",
    product: "Informe parcial o final de la prospectiva del programa académico",
    description: "Apoyar al trabajo de prospectiva del programa",
    consolidated: "Otras1",
  },

  {
    name: "Comité: Curricular",
    mission: "Docencia",
    convention: "Comités",
    product: "Acta de los comités",
    description: "Participación en el comité curricular",
    consolidated: "Comités2",
  },
  {
    name: "Comité: Trabajos de Grado",
    mission: "Investigación",
    convention: "Comités",
    product: "Acta de los comités",
    description: "Participación en el comité de trabajos de grado",
    consolidated: "Comités1",
  },
  {
    name: "Comité: Autoevaluación",
    mission: "Docencia",
    convention: "Comités",
    product: "Acta de los comités",
    description: "Participación en el comité de trabajos de autoevaluación",
    consolidated: "Comités2",
  },
  {
    name: "Comité: Investigación y Semilleros",
    mission: "Investigación",
    convention: "Comités",
    product: "Acta de los comités",
    description:
      "Participación en el comité de trabajos de investigación y semilleros",
    consolidated: "Comités1",
  },
  {
    name: "Extensión: Graduados",
    mission: "Extensión",
    convention: "Extensión",
    product: "Informe final del seguimiento e impacto a graduados",
    description: "Participar en el seguimiento en impacto de graduados",
    consolidated: "Extensión1",
  },
  {
    name: "Extensión: Práctica Social",
    mission: "Extensión",
    convention: "Extensión",
    product: "Informe parcial o final de practicas sociales",
    description: "Acompañar y asesorar las practicas sociales",
    consolidated: "Extensión2",
  },
  {
    name: "Extensión: Educación Continua",
    mission: "Extensión",
    convention: "Extensión",
    product: "Informe final de propuestas y desarrollo de educación continua",
    description: "Apoyar procesos de formación en educación continua",
    consolidated: "Extensión3",
  },
  {
    name: "Extensión: Emprendimiento",
    mission: "Extensión",
    convention: "Extensión",
    product: "Informe final de proyectos de emprendimiento",
    description: "Realizar actividades o proyectos de apoyo al emprendimiento",
    consolidated: "Extensión4",
  },
  {
    name: "Investigación: Trabajos de Grado",
    mission: "Investigación",
    convention: "Investigación",
    product:
      "Informe estadístico de modalidades de trabajo de grado desarrolladas",
    description:
      "Participar en el apoyo a asesorías de los trabajos de grado según la línea",
    consolidated: "Investigación4",
  },
  {
    name: "Investigación: Grupo de Investigación",
    mission: "Investigación",
    convention: "Investigación",
    product: "Informe parcial o final del proyecto de investigación",
    description: "Realizar actividades o proyectos de apoyo al emprendimiento",
    consolidated: "Investigación1",
  },
  {
    name: "Investigación: Semilleros",
    mission: "Investigación",
    convention: "Investigación",
    product:
      "Informes parciales o finales de actividades desarrolladas en los semilleros de investigación",
    description:
      "Participar en la consolidación de los semilleros de investigación",
    consolidated: "Investigación2",
  },

  {
    name: "Investigación: Condiciones de Registro Calificado",
    mission: "Investigación",
    convention: "Investigación",
    product:
      "Informes parciales o finales de las condiciones de registro calificado",
    description: "Construcción de condiciones 5 y 6 del programa académico",
    consolidated: "Investigación3",
  },
  {
    name: "Coordinación: Participación reunión equipo programa",
    mission: "Otros",
    convention: "Otras",
    product: "Actas y registros de asistencia",
    description: "Participar en las reuniones del programa",
    consolidated: "Comités2",
  },

  {
    name: "Gestión y ejecución de convenios",
    mission: "Otros",
    convention: "Otras",
    product: "Informe de la gestión y ejecución de convenios",
    description: "Gestionar y ejecutar convenios",
    consolidated: "Otras2",
  },
];

export const Asignaturas = [
  "ALGEBRA SUPERIOR",
  "BIOLOGIA",
  "BOTANICA TAXONOMICA Y DENDROLOGIA",
  "CALCULO DIFERENCIAL",
  "CALCULO INTEGRAL",
  "COMUNIDADES RURALES",
  "CULTIVOS AGRICOLAS",
  "CULTURA FISICA",
  "DASOMETRIA E INVENTARIO FORESTAL",
  "DISEÑO EXPERIMENTAL",
  "ECONOMIA Y VALORACION AGROFORESTAL",
  "EPISTEMOLOGIA",
  "ESTADISTICA",
  "ETICA",
  "FAUNA",
  "FISIOLOGIA VEGETAL",
  "FISIOLOGIA Y GENETICA ANIMAL",
  "INGLES I",
  "INGLES II",
  "LABORATORIO DE QUIMICA INORGANICA",
  "LABORATORIO DE QUIMICA ORGANICA",
  "LEGISLACION AGROPECUARIA Y FORESTAL",
  "MANEJO PECUARIO I",
  "MECANICA",
  "METEOROLOGIA TROPICAL",
  "PALMAS Y FRUTALES",
  "PRINCIPIOS DE AGROFORESTERIA",
  "PROCESOS DE LECTURA Y ESCRITURA",
  "QUIMICA INORGANICA",
  "QUIMICA ORGANICA",
  "SANIDAD AGROFORESTAL",
  "SEMINARIO DE GRADO I",
  "SEMINARIO DE GRADO II",
  "SILVICULTURA",
  "SISTEMAS AGROFORESTALES",
  "SISTEMAS DE PROPAGACION",
  "SUELOS",
  "TOPOGRAFIA Y CARTOGRAFIA",
];

export const Grupos = ["D161", "E161"];

export const Misionales = [
  "Docencia",
  "Investigación",
  "Extensión",
  "OACA",
  "ODA",
  "Comités",
  "Otras",
];
