export const Facultades = [
  "FCSE",
  "FCNI",
  "DPTO. DE CIENCIAS BÁSICAS",
  "DPTO. DE HUMANIDADES",
  "DPTO. DE IDIOMAS ",
];

export const TipoDeContrato = [
  "Carrera",
  "Tiempo completo",
  "Medio tiempo 11M",
  "Medio tiempo 4M",
];

export const Escalafon = [
  "Docente Experto",
  "Docente Auxiliar",
  "Docente Auxiliar 1",
  "Docente Asistente",
  "Docente Asociado",
  "Docente Titular",
];

export const Actividades = [
  {
    name: "Docencia Directa: Orientación de curso",
    mission: "Docencia",
    convention: "Docencia directa",
    product:
      "Plan de clase - acta de notas - guías orientadoras - parcial por corte",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Orientación de Módulo",
    mission: "Docencia",
    convention: "Docencia directa",
    product:
      "Plan de clase - acta de notas - guías orientadoras - parcial por corte",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Orientación de Módulo Virtual - Tutor",
    mission: "Docencia",
    convention: "Docencia directa",
    product: "Plan de modulo virtual",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Orientación de Módulo Virtual - Diseñador",
    mission: "Docencia",
    convention: "Docencia directa",
    product: "Diseño de modulo virtual",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Orientación de Módulo Virtual - Consejero",
    mission: "Docencia",
    convention: "Docencia directa",
    product: "Consejería a estudiantes",
    consolidated: "Docencia",
  },
  {
    name: "Docencia Directa: Tutorías",
    mission: "Docencia",
    convention: "Docencia directa",
    product: "Informe final de la atención de tutorías de curso",
    description: "Tutoría en acompañamiento a estudiante",
    consolidated: "ODA7",
  },
  {
    name: "Preparación de clase: Metodología Pedagógica del Curso",
    mission: "Docencia",
    convention: "Otras",
    product: "Guías - talleres - métodos de aprendizajes",
    description: "Diseño metodológico del curso",
    consolidated: "Otras2",
  },
  {
    name: "Preparación de módulo: Metodología Pedagógica del Módulo",
    mission: "Docencia",
    convention: "Otras",
    product: "Guías - talleres - métodos de aprendizajes",
    description: "Diseño metodológico del módulo",
    consolidated: "Otras2",
  },
  {
    name: "ODA: PAD",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "Informe final del proyecto Acompañamiento Docente",
    description: "Proyecto acompañamiento docente",
    consolidated: "ODA1",
  },
  {
    name: "ODA: PAE",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "Informe final del proyecto Acompañamiento Docente",
    description: "Proyecto acompañamiento estudiante",
    consolidated: "ODA2",
  },
  {
    name: "ODA: Capacitación Docente",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "producto final del seminario o módulo",
    description: "Participación en los cursos ofertados por la ODA",
    consolidated: "ODA8",
  },
  {
    name: "ODA: Evaluación Curricular",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "producto final de la evaluación curricular del programa",
    description: "Desarrollar la evaluación curricular del programa",
    consolidated: "ODA3",
  },
  {
    name: "ODA: Diseño o Rediseño Plan de Curso",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "Entrega final del plan de curso del programa",
    description: "Elaboración del plan de curso",
    consolidated: "ODA4",
  },
  {
    name: "ODA: Renovación de Registro Calificado",
    mission: "Docencia",
    convention: "Procesos ODA",
    product: "Entrega final de las condiciones curriculares",
    description: "Construir las condiciones curriculares",
    consolidated: "ODA4",
  },
  {
    name: "Colectivo Docente: Plan de Clase",
    mission: "Docencia",
    convention: "Otras",
    product:
      "Actas de reunion - socialización de la línea del área de conocimiento",
    description: "Elaboración del plan de clase del curso",
    consolidated: "Otras3",
  },
  {
    name: "Colectivo Docente: Instrumento de Evaluación",
    mission: "Docencia",
    convention: "Otras",
    product: "Actas de reunion - instrumentos de evaluación",
    description:
      "Proponer temáticas para el desarrollo del instrumento de evaluación",
    consolidated: "Otras3",
  },
  {
    name: "Colectivo Docente: Permanencia",
    mission: "Docencia",
    convention: "Otras",
    product: "Informe de permanencia por corte",
    description: "Aplicar estrategias para la permanencia",
    consolidated: "Otras3",
  },
  {
    name: "Oficina de las Tic: Diseño de Módulos",
    mission: "Docencia",
    convention: "Otras",
    product: "Diseño de módulos del área de conocimiento",
    description: "Elaboración de módulos virtuales",
    consolidated: "Otras2",
  },
  {
    name: "OACA: Registro Calificado",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Entrega final de las condiciones institucionales y del programa",
    description: "Construir las condiciones institucionales y del programa",
    consolidated: "OACA1",
  },
  {
    name: "OACA: Renovación de Registro Calificado",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Entrega final de las condiciones institucionales  y del programa",
    description: "Construir las condiciones institucionales y del programa",
    consolidated: "OACA1",
  },
  {
    name: "OACA: Condiciones Iniciales",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Informe parcial o final de las condiciones iniciales",
    description:
      "Apoyo al proceso de cumplimiento de las condiciones iniciales",
    consolidated: "OACA3",
  },
  {
    name: "OACA: Acreditación",
    mission: "Docencia",
    convention: "Procesos OACA",
    product:
      "Informe parcial o final del documento de acreditación institucional y del programa",
    description:
      "Apoyo al proceso de acreditación del programa y de la institución",
    consolidated: "OACA4",
  },
  {
    name: "OACA: Autoevaluación Institucional",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Informe parcial o final de autoevaluación institucional",
    description: "Apoyar al proceso de autoevaluación institucional",
    consolidated: "OACA5",
  },
  {
    name: "OACA: Autoevaluación de Programa",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "Informe parcial o final de autoevaluación del programa",
    description: "Apoyar al proceso de autoevaluación del programa",
    consolidated: "OACA2",
  },
  {
    name: "OACA: Vigía de Calidad",
    mission: "Docencia",
    convention: "Procesos OACA",
    product: "No aplica",
    description:
      "Apoyo a los procesos de calidad del programa y de la institución",
    consolidated: "OACA6",
  },
  {
    name: "Prospectiva: Del programa académico",
    mission: "Otros",
    convention: "Otras",
    product: "Informe parcial o final de la prospectiva del programa académico",
    description: "Apoyar al trabajo de prospectiva del programa",
    consolidated: "Otras1",
  },

  {
    name: "Comité: Curricular",
    mission: "Docencia",
    convention: "Comités",
    product: "Acta de los comités",
    description: "Participación en el comité curricular",
    consolidated: "Comités2",
  },
  {
    name: "Comité: Trabajos de Grado",
    mission: "Investigación",
    convention: "Comités",
    product: "Acta de los comités",
    description: "Participación en el comité de trabajos de grado",
    consolidated: "Comités1",
  },
  {
    name: "Comité: Autoevaluación",
    mission: "Docencia",
    convention: "Comités",
    product: "Acta de los comités",
    description: "Participación en el comité de trabajos de autoevaluación",
    consolidated: "Comités2",
  },
  {
    name: "Comité: Investigación y Semilleros",
    mission: "Investigación",
    convention: "Comités",
    product: "Acta de los comités",
    description:
      "Participación en el comité de trabajos de investigación y semilleros",
    consolidated: "Comités1",
  },
  {
    name: "Extensión: Graduados",
    mission: "Extensión",
    convention: "Extensión",
    product: "Informe final del seguimiento e impacto a graduados",
    description: "Participar en el seguimiento en impacto de graduados",
    consolidated: "Extensión1",
  },
  {
    name: "Extensión: Práctica Social",
    mission: "Extensión",
    convention: "Extensión",
    product: "Informe parcial o final de practicas sociales",
    description: "Acompañar y asesorar las practicas sociales",
    consolidated: "Extensión2",
  },
  {
    name: "Extensión: Educación Continua",
    mission: "Extensión",
    convention: "Extensión",
    product: "Informe final de propuestas y desarrollo de educación continua",
    description: "Apoyar procesos de formación en educación continua",
    consolidated: "Extensión3",
  },
  {
    name: "Extensión: Emprendimiento",
    mission: "Extensión",
    convention: "Extensión",
    product: "Informe final de proyectos de emprendimiento",
    description: "Realizar actividades o proyectos de apoyo al emprendimiento",
    consolidated: "Extensión4",
  },
  {
    name: "Investigación: Trabajos de Grado",
    mission: "Investigación",
    convention: "Investigación",
    product:
      "Informe estadístico de modalidades de trabajo de grado desarrolladas",
    description:
      "Participar en el apoyo a asesorías de los trabajos de grado según la línea",
    consolidated: "Investigación4",
  },
  {
    name: "Investigación: Grupo de Investigación",
    mission: "Investigación",
    convention: "Investigación",
    product: "Informe parcial o final del proyecto de investigación",
    description: "Realizar actividades o proyectos de apoyo al emprendimiento",
    consolidated: "Investigación1",
  },
  {
    name: "Investigación: Semilleros",
    mission: "Investigación",
    convention: "Investigación",
    product:
      "Informes parciales o finales de actividades desarrolladas en los semilleros de investigación",
    description:
      "Participar en la consolidación de los semilleros de investigación",
    consolidated: "Investigación2",
  },

  {
    name: "Investigación: Condiciones de Registro Calificado",
    mission: "Investigación",
    convention: "Investigación",
    product:
      "Informes parciales o finales de las condiciones de registro calificado",
    description: "Construcción de condiciones 5 y 6 del programa académico",
    consolidated: "Investigación3",
  },
  {
    name: "Coordinación: Participación reunión equipo programa",
    mission: "Otros",
    convention: "Otras",
    product: "Actas y registros de asistencia",
    description: "Participar en las reuniones del programa",
    consolidated: "Comités2",
  },

  {
    name: "Gestión y ejecución de convenios",
    mission: "Otros",
    convention: "Otras",
    product: "Informe de la gestión y ejecución de convenios",
    description: "Gestionar y ejecutar convenios",
    consolidated: "Otras2",
  },
];

export const Asignaturas = [
  "(M.I) III Gestión Investigativa para la Toma de Decisiones",
  "Administración Ambiental y Desarrollo Sostenible",
  "Administración de Empresas",
  "Administración de Proyectos",
  "Administración Pública",
  "Análisis Financiero",
  "Arte, Cultura y Sociedad",
  "Auditoria y la Gestión de los Recursos",
  "Cálculo",
  "Calidad de Software",
  "Ciencia, Tecnología y Sociedad",
  "Contabilidad de Inventario",
  "Contabilidad de Propiedad Planta y Equipo",
  "Contabilidad Financiera I",
  "Contabilidad Pública NICSP",
  "Contratación Estatal y Herramientas Digitales de Sistemas de Información Pública",
  "Control Fiscal Estatal",
  "Costos",
  "Costos y Presupuestos",
  "Creatividad",
  "Cultura Ética Empresarial",
  "Desarrollo de Bienes y Servicios",
  "Desarrollo de la Organización",
  "Desarrollo de Proyectos",
  "Desarrollo Local",
  "Dibujo Asistido por Computador",
  "Ecuaciones Diferenciales",
  "El Marketing en la Empresa",
  "Estrategia de Negocio",
  "Estrategias en las Organizaciones",
  "Ética",
  "Evaluación de Proyectos",
  "Fundamentos de la Administración",
  "Fundamentos de la Creatividad y Emprendimiento",
  "Fundamentos de Macroeconomía",
  "Fundamentos de Marketing",
  "Fundamentos de Microeconomía",
  "Fundamentos del Sector Público",
  "Fundamentos Financieros",
  "Fundamentos Integrales de Contabilidad",
  "Gerencia Estratégica",
  "Gerencia Estratégica Comercial",
  "Gerencia Estratégica Relacional",
  "Gestión de Activos con Enfoque Tributario",
  "Gestión Organizacional",
  "Gestión Pública",
  "Habilidades de Negociación",
  "Identidad Uteista",
  "Informática Empresarial",
  "Innovación Empresarial",
  "Innovación Sostenible",
  "Innovación y desarrollo de Producto",
  "Introducción a la Administración",
  "Introducción a la Administración Pública",
  "Investigación Contable",
  "Investigación de Mercados Cualitativa",
  "Investigación de Mercados Cuantitativas",
  "Investigación en Operaciones",
  "IV Tiempos y Movimientos Comerciales",
  "La Administración Estatal y Finanzas Públicas",
  "La Administración Estatal y la Revisoría",
  "La Administración Estratégica",
  "La Contabilidad de las Empresas y los Sistemas de Información",
  "La Gestión de las Organizaciones",
  "Liderazgo Social y Empresarial",
  "Macroeconomía",
  "Marketing Digital",
  "Marketing Digital E-Commerce",
  "Marketing Social y Relacional",
  "Marketing Sustentable",
  "Matemática Básica",
  "Metodología de la Investigación",
  "Metodología de la Investigación I",
  "Microeconomía",
  "Modulo Integrador Contabilidad Producción y Mercadeo",
  "Modulo Integrador Control y Análisis de la Información",
  "Modulo Integrador Fundamentos de la Organización",
  "Modulo Integrador la Fiscalidad y Los Activos",
  "Modulo Integrador la Fiscalidad y Los Pasivos",
  "Modulo Integrador Laboratorio Empresarial",
  "Negocios en su Contexto",
  "Negocios Sostenibles",
  "Organización y Dirección",
  "Organizaciones en el Contexto Global",
  "Pasivo, Fiscalidad y Cuentas Patrimoniales",
  "Planeación Estratégica",
  "Planeación Pública",
  "Procesos Contables Especiales I",
  "Procesos Contables Especiales II",
  "Procesos Empresariales",
  "Procesos Estratégicos",
  "Producción de Textos",
  "Proyecto de Inversión",
  "Riesgos Geológicos",
  "Seminario de Grado III",
  "Seminario de Grado IV",
];

export const Grupos = [
  "A001",
  "A002",
  "A003",
  "A004",
  "A005",
  "A006",
  "A007",
  "A008",
  "A011",
  "A041",
  "A041R",
  "A042",
  "A043",
  "A044",
  "A045",
  "A046",
  "A047",
  "A048",
  "A051",
  "A051A",
  "A051R",
  "A052",
  "A061",
  "A061A",
  "A062",
  "A062A",
  "A063",
  "A063A",
  "A081",
  "A082",
  "A083",
  "A101",
  "A101R",
  "A102",
  "A103",
  "A104",
  "A105",
  "A111",
  "A112",
  "A113",
  "A114",
  "A115",
  "A116",
  "A118",
  "A118A",
  "A119",
  "A131",
  "A132",
  "A133",
  "A134",
  "A135",
  "A136",
  "A137",
  "A138",
  "A141",
  "A142",
  "A143",
  "A144",
  "A145",
  "A151",
  "A152",
  "A171",
  "A171A",
  "A171B",
  "A181",
  "A181A",
  "A182",
  "A191",
  "A191P",
  "A192",
  "A192P",
  "A193",
  "A193P",
  "A194",
  "A195",
  "A196",
  "A197",
  "A231",
  "A241",
  "A242",
  "A251",
  "A251R",
  "A252",
  "A253",
  "A254",
  "A255",
  "B001",
  "B002",
  "B003",
  "B004",
  "B041",
  "B041R",
  "B042",
  "B043",
  "B044",
  "B045",
  "B051R",
  "B061",
  "B062",
  "B063",
  "B063A",
  "B081",
  "B081A",
  "B082",
  "B082A",
  "B083",
  "B084",
  "B101",
  "B102",
  "B103",
  "B104",
  "B111",
  "B111A",
  "B112",
  "B112A",
  "B112R",
  "B113",
  "B113A",
  "B114",
  "B115",
  "B117",
  "B118",
  "B119",
  "B131",
  "B132",
  "B133",
  "B134",
  "B135",
  "B136",
  "B137",
  "B139",
  "B141",
  "B151",
  "B152",
  "B161",
  "B162",
  "B172",
  "B172A",
  "B181",
  "B181A",
  "B182",
  "B182A",
  "B183R",
  "B191",
  "B191P",
  "B192",
  "B192P",
  "B193",
  "B193P",
  "B194",
  "B194P",
  "B195",
  "B196",
  "B197",
  "B198",
  "B198P",
  "B199",
  "B241",
  "B242",
  "B243",
  "B244",
  "B245",
  "B246",
  "B251",
  "B251A",
  "B251R",
  "B252",
  "B252A",
  "B253",
  "B253A",
  "B254",
  "B254A",
  "B255",
  "B255A",
  "B281",
  "B282",
  "C101",
  "C111",
  "C112",
  "CVA003",
  "CVA007",
  "CVA008",
  "CVE003",
  "CVE007",
  "CVE008-1",
  "CVE008-2",
  "CVE010",
  "CVE011",
  "CVE012",
  "CVE614",
  "D001",
  "D001-D",
  "D002",
  "D003",
  "D004",
  "D005R",
  "D041",
  "D041-D",
  "D041R",
  "D042",
  "D043",
  "D044",
  "D045",
  "D046",
  "D051R",
  "D061",
  "D062",
  "D063",
  "D063 A",
  "D063A",
  "D064",
  "D065",
  "D081",
  "D081A",
  "D082",
  "D082A",
  "D083",
  "D083R",
  "D084",
  "D084R",
  "D085R",
  "D086R",
  "D087R",
  "D101",
  "D102",
  "D103",
  "D111",
  "D111A",
  "D111B",
  "D112",
  "D113",
  "D113A",
  "D114",
  "D115",
  "D116",
  "D117",
  "D117B",
  "D117C",
  "D118",
  "D118A",
  "D119",
  "D119A",
  "D131",
  "D132",
  "D133",
  "D134",
  "D135",
  "D136",
  "D137",
  "D141",
  "D142",
  "D151",
  "D152",
  "D161",
  "D162",
  "D173",
  "D173A",
  "D174",
  "D174A",
  "D175",
  "D181",
  "D181A",
  "D182",
  "D182A",
  "D191",
  "D191A",
  "D191B",
  "D191P",
  "D192",
  "D192A",
  "D192P",
  "D193",
  "D193A",
  "D193P",
  "D194",
  "D194P",
  "D195",
  "D196",
  "D197",
  "D199",
  "D241",
  "D242",
  "D243",
  "D244",
  "D251",
  "D251A",
  "D252",
  "D252A",
  "D253",
  "D253R",
  "D254",
  "D281",
  "D281R",
  "D282",
  "E001",
  "E001D",
  "E001-R",
  "E002",
  "E003",
  "E004",
  "E005",
  "E006",
  "E006R",
  "E007",
  "E007R",
  "E008",
  "E011",
  "E012",
  "E013",
  "E014",
  "E015",
  "E016",
  "E041",
  "E041A",
  "E041R",
  "E041-R",
  "E042",
  "E043",
  "E044",
  "E045",
  "E046",
  "E047",
  "E048",
  "E051",
  "E051A",
  "E052",
  "E052A",
  "E053",
  "E053A",
  "E054",
  "E055",
  "E056",
  "E061",
  "E061A",
  "E062",
  "E062A",
  "E063",
  "E063A",
  "E064",
  "E065",
  "E081",
  "E081A",
  "E082",
  "E082A",
  "E083",
  "E083R",
  "E084",
  "E084R",
  "E085",
  "E086",
  "E087",
  "E088",
  "E089",
  "E091",
  "E092",
  "E093",
  "E101",
  "E101R",
  "E102",
  "E102R",
  "E103",
  "E103R",
  "E104",
  "E111",
  "E111A",
  "E111B",
  "E111D",
  "E111P",
  "E111-R",
  "E112",
  "E112A",
  "E113",
  "E113A",
  "E114",
  "E114A",
  "E115",
  "E116",
  "E117",
  "E117A",
  "E117B",
  "E118",
  "E119",
  "E120",
  "E131",
  "E131A",
  "E132",
  "E133",
  "E133A",
  "E134",
  "E135",
  "E136",
  "E139",
  "E141",
  "E142",
  "E143",
  "E144",
  "E145",
  "E146",
  "E147",
  "E149",
  "E151",
  "E151A",
  "E152",
  "E161",
  "E162",
  "E171",
  "E171A",
  "E171B",
  "E172",
  "E172A",
  "E173",
  "E173A",
  "E173B",
  "E174",
  "E174A",
  "E174B",
  "E175",
  "E175A",
  "E175B",
  "E176",
  "E176A",
  "E176B",
  "E177",
  "E178",
  "E178A",
  "E179",
  "E180",
  "E181",
  "E181A",
  "E191",
  "E191P",
  "E192",
  "E192A",
  "E192P",
  "E193",
  "E193A",
  "E193P",
  "E194",
  "E194P",
  "E195",
  "E196",
  "E197",
  "E197P",
  "E198",
  "E199",
  "E241",
  "E242",
  "E251",
  "E251A",
  "E251R",
  "E252",
  "E252R",
  "E253",
  "E253R",
  "E254",
  "E254R",
  "E255",
  "E255A",
  "E255R",
  "E256",
  "E256R",
  "E261",
  "E261-R",
  "E262",
  "E263",
  "E271",
  "E281",
  "E282",
  "PAE-V041",
  "PAE-V042",
  "PAE-V043",
  "PAE-V044",
  "PCP-V001",
  "PCP-V002",
  "PCP-V010",
  "TCF-V001",
  "TCF-V002",
  "TCF-V003",
  "TCF-V010",
  "TEM202",
  "TGE-V041",
  "TGE-V042",
  "TGE-V043",
  "TGE-V044",
  "TMG-V061",
  "TMG-V065",
];

export const Misionales = [
  "Docencia",
  "Investigación",
  "Extensión",
  "OACA",
  "ODA",
  "Comités",
  "Otras",
];
